(function($){$.widget("abaxx.contextmenu",{options:{triggerEvent:"contextmenu",trigger:null,menuId:null,zIndex:1,lazy:true,dropDownMenuClass:"drop-down-menu",contextMenuClass:"context-menu",anchor:null},contextEventTarget:null,_timer:null,_deferredClose:function(element){var self=this;if(self._timer)window.clearTimeout(self._timer);self._timer=window.setTimeout(function(){self._hide(element)},250)},_generateId:function(){for(var id="contextmenu_"+Math.floor(Math.random()*1E3);document.getElementById(id);)id=
"contextmenu_"+Math.floor(Math.random()*1E3);return id},_removeOrphans:function(base){var menuId=this.options.menuId;base.each(function(index,element){var oldMenu;var oldElement;oldMenu=jQuery(element).data("contextmenu");if(oldMenu&&oldMenu.destroy){oldMenu.destroy();jQuery(element).data("contextmenu",null)}if(menuId){oldElement=document.getElementById(menuId);if(oldElement){oldMenu=jQuery(oldElement).data("contextmenu");if(oldMenu&&oldMenu.destroy)oldMenu.destroy();jQuery(oldElement).remove()}}})},
_setupTrigger:function(triggerEvent,triggerSelector){var self=this;var $trigger;if(jQuery.isPlainObject(triggerSelector))jQuery.each(triggerSelector,function(eventName,selector){if(triggerSelector.hasOwnProperty(eventName)&&selector)self._setupTrigger(eventName,selector)});else{$trigger=jQuery(triggerSelector);this._removeOrphans($trigger);$trigger.data("contextmenu",this).on(triggerEvent+this.eventNamespace,function(event){self.show(event)});$trigger.find("a").on("click",function(event){if(event.ctrlKey){event.stopPropagation();
event.preventDefault()}});this.trigger=(this.trigger||jQuery()).add(triggerSelector)}},_removeTrigger:function(){this.trigger.off(this.eventNamespace)},_create:function(){var self=this;this.rendered=false;this.options.menuId=(this.options.menuId||this._generateId()).replace(/[:.\s]/g,"_");this.eventNamespace=".contextmenu"+this.options.menuId;this.element.hide().addClass("ui-menu ui-widget ui-widget-content ui-corner-all").css({position:"absolute",zIndex:this.options.zIndex});this._setupTrigger(this.options.triggerEvent,
this.options.trigger);if(!this.options.lazy)this.render();jQuery(this.element).on("mouseenter"+this.eventNamespace,".ui-menu-item",function(){jQuery(this).addClass("ui-state-focus").parents(".ui-menu-item").addClass("ui-state-active")}).on("mouseleave"+this.eventNamespace,".ui-menu-item",function(){jQuery(this).removeClass("ui-state-focus").parents(".ui-menu-item").removeClass("ui-state-active")}).on("mouseenter"+this.eventNamespace,".has-submenu",jQuery.proxy(self._showSubMenu,self)).on("mouseleave"+
this.eventNamespace,".has-submenu",function(){self._deferredClose(jQuery(this).find("\x3e .submenu")[0])});jQuery(document).on("contextmenu-closeall"+this.eventNamespace,function(event){if(event.target!==self.element[0])self.close()}).on("keyup"+this.eventNamespace,function(event){if(event.keyCode===27)self.close()})},_destroy:function(){jQuery(document).off(this.eventNamespace);this._removeTrigger()},_showSubMenu:function(event){var $parent=jQuery(event.currentTarget);var $submenu=$parent.find("\x3e .ui-menu");
$parent.siblings(".has-submenu").each(function(i,siblingMenu){jQuery(siblingMenu).removeClass("ui-state-active").find("\x3e .submenu:visible").removeClass("ui-state-active").hide()});$submenu.addClass("ui-state-active").show().position({my:"left top",at:"right top",of:$parent})},_hide:function(submenu){jQuery(submenu).removeClass("ui-state-active").hide()},_menuItemClicked:function(event){var $item=jQuery(event.currentTarget);var itemData=$item.data("contextmenuitem");var disabled=$item.is(".ui-state-disabled");
var eventHandled=false;var $anchor;if(!disabled)if(jQuery.isFunction(itemData.onclick)){itemData.onclick.call(this,event);eventHandled=true}else if(jQuery.isPlainObject(itemData.onclick)&&jQuery.isFunction(itemData.onclick.fn)){itemData.onclick.fn.call(itemData.onclick.scope||this,"click",event,itemData.onclick.obj||this);eventHandled=true}else if(itemData.url&&jQuery(event.target).is(":not(a)")){eventHandled=true;$anchor=$item.find("a[href]");if($anchor.length>0)$anchor[0].click()}this.close();if(eventHandled||
disabled){event.preventDefault();event.stopPropagation()}},_buildMenu:function($menu,menuId,itemData){var self=this;var $subMenuElement;var $item;var subMenuIndicator="\x3cspan class\x3d'ui-menu-icon ui-icon ui-icon-carat-1-e'\x3e\x3c/span\x3e";var helpTextWrapper="\x3cem class\x3d'helptext'\x3e\x3c/em\x3e";if(menuId)$menu.attr("id",menuId);jQuery.each(itemData,function(index,item){if(jQuery.isArray(item)){if(index>0)$menu.append(jQuery.parseHTML("\x3cli class\x3d'ui-menu-divider ui-corner-all'\x3e\x3c/li\x3e"));
self._buildMenu($menu,menuId,item)}else{$item=jQuery(jQuery.parseHTML("\x3cli class\x3d'ui-menu-item ui-corner-all'\x3e\x3ca href\x3d'#'\x3e"+item.text+"\x3c/a\x3e\x3c/li\x3e"));$item.toggleClass("ui-state-disabled",item.disabled===true);if(item.classname)$item.addClass(item.classname);if(item.id)$item.attr("id",item.id);if(item.url)$item.find("\x3e a").attr("href",item.url);if(item.title)$item.attr("title",item.title);$item.data("contextmenuitem",item).click(jQuery.proxy(self._menuItemClicked,self));
if(item.submenu){$subMenuElement=jQuery(jQuery.parseHTML("\x3cul class\x3d'ui-menu ui-widget ui-widget-content ui-corner-all submenu' /\x3e"));$subMenuElement.hide().css("position","absolute");$item.find("\x3e a").append(subMenuIndicator);$item.addClass("has-submenu").append(self._buildMenu($subMenuElement,item.submenu.id,item.submenu.itemData));if(item.disabled)$item.find(".ui-menu-item").addClass("ui-state-disabled");if(item.submenu.classname)$subMenuElement.addClass(item.submenu.classname)}else if(item.helptext)jQuery(jQuery.parseHTML(helpTextWrapper)).html(item.helptext).appendTo($item.find("\x3e a"));
$item.appendTo($menu)}});return $menu},close:function(){var closeEvent=jQuery.Event("contextmenuclose");if(jQuery.isFunction(this.options.close))if(this.options.close.call(this.element,closeEvent,this)===false)closeEvent.preventDefault();jQuery(this.contextEventTarget).trigger(closeEvent,this);if(!closeEvent.isDefaultPrevented()){this.element.hide().find("\x3e .ui-state-active").removeClass("ui-state-active");if(this.options.highlightedTriggerClass)jQuery(this.contextEventTarget).removeClass(this.options.highlightedTriggerClass);
this.contextEventTarget=null}},render:function(){if(this.options.itemData){this.element.html("");this._buildMenu(this.element,this.options.menuId,this.options.itemData)}if(this.options.classname)this.element.addClass(this.options.classname);this.element.prependTo(document.body);this.rendered=true},_findContextEventTarget:function(event){var target;if(this.options.restriction)target=jQuery(event.target).closest(this.options.restriction)[0];else target=event.target;return target},show:function(event){var self=
this;var beforeShowEvent=jQuery.Event("contextmenubeforeshow");var oldContextEventTarget;if(event){oldContextEventTarget=self.contextEventTarget;self.contextEventTarget=self._findContextEventTarget(event);if(self.contextEventTarget){if(jQuery.isFunction(self.options.beforeShow))if(self.options.beforeShow.call(self.element,beforeShowEvent,self)===false)beforeShowEvent.preventDefault();jQuery(self.contextEventTarget).trigger(beforeShowEvent,self);if(!beforeShowEvent.isDefaultPrevented()){if(!this.rendered)this.render();
if(this.options.highlightedTriggerClass){if(oldContextEventTarget)jQuery(oldContextEventTarget).removeClass(this.options.highlightedTriggerClass);jQuery(self.contextEventTarget).addClass(this.options.highlightedTriggerClass)}this.element.trigger(jQuery.Event("contextmenu-closeall")).toggleClass(this.options.dropDownMenuClass,event.type==="click").toggleClass(this.options.contextMenuClass,event.type==="contextmenu").prependTo(document.body).show().position({my:"left top",at:"left bottom",of:this.options.anchor?
this.options.anchor:event.type==="contextmenu"?event:event.currentTarget,collision:"flipfit",offset:this.options.anchor?"0 "+this.options.anchor.css("margin-bottom"):event.type==="contextmenu"?"0 10":null});jQuery(document).one("click.contextmenu",function(){self.close()});jQuery(window).resize(function(){self.close()});if(jQuery.isFunction(self.options.show))self.options.show.call(self.element,beforeShowEvent,self)}}event.preventDefault();event.stopPropagation()}},eachMenuItem:function(visitor){this.element.find("li").each(visitor)}})})(jQuery);
(function(factory){if(typeof define==="function"&&define.amd)define(["jquery"],factory);else factory(typeof jQuery!="undefined"?jQuery:window.Zepto)})(function($){function doAjaxSubmit(e){var options=e.data;if(!e.isDefaultPrevented()){e.preventDefault();$(e.target).ajaxSubmit(options)}}function captureSubmittingElement(e){var target=e.target;var $el=$(target);if(!$el.is("[type\x3dsubmit],[type\x3dimage]")){var t=$el.closest("[type\x3dsubmit]");if(t.length===0)return;target=t[0]}var form=this;form.clk=
target;if(target.type=="image")if(e.offsetX!==undefined){form.clk_x=e.offsetX;form.clk_y=e.offsetY}else if(typeof $.fn.offset=="function"){var offset=$el.offset();form.clk_x=e.pageX-offset.left;form.clk_y=e.pageY-offset.top}else{form.clk_x=e.pageX-target.offsetLeft;form.clk_y=e.pageY-target.offsetTop}setTimeout(function(){form.clk=form.clk_x=form.clk_y=null},100)}function log(){if(!$.fn.ajaxSubmit.debug)return;var msg="[jquery.form] "+Array.prototype.join.call(arguments,"");if(window.console&&window.console.log)window.console.log(msg);
else if(window.opera&&window.opera.postError)window.opera.postError(msg)}var feature={};feature.fileapi=$("\x3cinput type\x3d'file'/\x3e").get(0).files!==undefined;feature.formdata=window.FormData!==undefined;var hasProp=!!$.fn.prop;$.fn.attr2=function(){if(!hasProp)return this.attr.apply(this,arguments);var val=this.prop.apply(this,arguments);if(val&&val.jquery||typeof val==="string")return val;return this.attr.apply(this,arguments)};$.fn.ajaxSubmit=function(options){function deepSerialize(extraData){var serialized=
$.param(extraData,options.traditional).split("\x26");var len=serialized.length;var result=[];var i;var part;for(i=0;i<len;i++){serialized[i]=serialized[i].replace(/\+/g," ");part=serialized[i].split("\x3d");result.push([decodeURIComponent(part[0]),decodeURIComponent(part[1])])}return result}function fileUploadXhr(a){var formdata=new FormData;for(var i=0;i<a.length;i++)formdata.append(a[i].name,a[i].value);if(options.extraData){var serializedData=deepSerialize(options.extraData);for(i=0;i<serializedData.length;i++)if(serializedData[i])formdata.append(serializedData[i][0],
serializedData[i][1])}options.data=null;var s=$.extend(true,{},$.ajaxSettings,options,{contentType:false,processData:false,cache:false,type:method||"POST"});if(options.uploadProgress)s.xhr=function(){var xhr=$.ajaxSettings.xhr();if(xhr.upload)xhr.upload.addEventListener("progress",function(event){var percent=0;var position=event.loaded||event.position;var total=event.total;if(event.lengthComputable)percent=Math.ceil(position/total*100);options.uploadProgress(event,position,total,percent)},false);
return xhr};s.data=null;var beforeSend=s.beforeSend;s.beforeSend=function(xhr,o){if(options.formData)o.data=options.formData;else o.data=formdata;if(beforeSend)beforeSend.call(this,xhr,o)};return $.ajax(s)}function fileUploadIframe(a$$0){function getDoc(frame){var doc=null;try{if(frame.contentWindow)doc=frame.contentWindow.document}catch(err){log("cannot get iframe.contentWindow document: "+err)}if(doc)return doc;try{doc=frame.contentDocument?frame.contentDocument:frame.document}catch(err$$0){log("cannot get iframe.contentDocument: "+
err$$0);doc=frame.document}return doc}function doSubmit(){function checkState(){try{var state=getDoc(io).readyState;log("state \x3d "+state);if(state&&state.toLowerCase()=="uninitialized")setTimeout(checkState,50)}catch(e){log("Server abort: ",e," (",e.name,")");cb(SERVER_ABORT);if(timeoutHandle)clearTimeout(timeoutHandle);timeoutHandle=undefined}}var t=$form.attr2("target");var a=$form.attr2("action");var mp="multipart/form-data";var et=$form.attr("enctype")||$form.attr("encoding")||mp;form.setAttribute("target",
id);if(!method||/post/i.test(method))form.setAttribute("method","POST");if(a!=s$$0.url)form.setAttribute("action",s$$0.url);if(!s$$0.skipEncodingOverride&&(!method||/post/i.test(method)))$form.attr({encoding:"multipart/form-data",enctype:"multipart/form-data"});if(s$$0.timeout)timeoutHandle=setTimeout(function(){timedOut=true;cb(CLIENT_TIMEOUT_ABORT)},s$$0.timeout);var extraInputs=[];try{if(s$$0.extraData)for(var n in s$$0.extraData)if(s$$0.extraData.hasOwnProperty(n))if($.isPlainObject(s$$0.extraData[n])&&
s$$0.extraData[n].hasOwnProperty("name")&&s$$0.extraData[n].hasOwnProperty("value"))extraInputs.push($('\x3cinput type\x3d"hidden" name\x3d"'+s$$0.extraData[n].name+'"\x3e').val(s$$0.extraData[n].value).appendTo(form)[0]);else extraInputs.push($('\x3cinput type\x3d"hidden" name\x3d"'+n+'"\x3e').val(s$$0.extraData[n]).appendTo(form)[0]);if(!s$$0.iframeTarget)$io.appendTo("body");if(io.attachEvent)io.attachEvent("onload",cb);else io.addEventListener("load",cb,false);setTimeout(checkState,15);try{form.submit()}catch(err){var submitFn=
document.createElement("form").submit;submitFn.apply(form)}}finally{form.setAttribute("action",a);form.setAttribute("enctype",et);if(t)form.setAttribute("target",t);else $form.removeAttr("target");$(extraInputs).remove()}}function cb(e){if(xhr$$0.aborted||callbackProcessed)return;doc=getDoc(io);if(!doc){log("cannot access response document");e=SERVER_ABORT}if(e===CLIENT_TIMEOUT_ABORT&&xhr$$0){xhr$$0.abort("timeout");deferred.reject(xhr$$0,"timeout");return}else if(e==SERVER_ABORT&&xhr$$0){xhr$$0.abort("server abort");
deferred.reject(xhr$$0,"error","server abort");return}if(!doc||doc.location.href==s$$0.iframeSrc)if(!timedOut)return;if(io.detachEvent)io.detachEvent("onload",cb);else io.removeEventListener("load",cb,false);var status="success";var errMsg;try{if(timedOut)throw"timeout";var isXml=s$$0.dataType=="xml"||doc.XMLDocument||$.isXMLDoc(doc);log("isXml\x3d"+isXml);if(!isXml&&window.opera&&(doc.body===null||!doc.body.innerHTML))if(--domCheckCount){log("requeing onLoad callback, DOM not available");setTimeout(cb,
250);return}var docRoot=doc.body?doc.body:doc.documentElement;xhr$$0.responseText=docRoot?docRoot.innerHTML:null;xhr$$0.responseXML=doc.XMLDocument?doc.XMLDocument:doc;if(isXml)s$$0.dataType="xml";xhr$$0.getResponseHeader=function(header){var headers={"content-type":s$$0.dataType};return headers[header.toLowerCase()]};if(docRoot){xhr$$0.status=Number(docRoot.getAttribute("status"))||xhr$$0.status;xhr$$0.statusText=docRoot.getAttribute("statusText")||xhr$$0.statusText}var dt=(s$$0.dataType||"").toLowerCase();
var scr=/(json|script|text)/.test(dt);if(scr||s$$0.textarea){var ta=doc.getElementsByTagName("textarea")[0];if(ta){xhr$$0.responseText=ta.value;xhr$$0.status=Number(ta.getAttribute("status"))||xhr$$0.status;xhr$$0.statusText=ta.getAttribute("statusText")||xhr$$0.statusText}else if(scr){var pre=doc.getElementsByTagName("pre")[0];var b=doc.getElementsByTagName("body")[0];if(pre)xhr$$0.responseText=pre.textContent?pre.textContent:pre.innerText;else if(b)xhr$$0.responseText=b.textContent?b.textContent:
b.innerText}}else if(dt=="xml"&&!xhr$$0.responseXML&&xhr$$0.responseText)xhr$$0.responseXML=toXml(xhr$$0.responseText);try{data=httpData(xhr$$0,dt,s$$0)}catch(err){status="parsererror";xhr$$0.error=errMsg=err||status}}catch(err$$0){log("error caught: ",err$$0);status="error";xhr$$0.error=errMsg=err$$0||status}if(xhr$$0.aborted){log("upload aborted");status=null}if(xhr$$0.status)status=xhr$$0.status>=200&&xhr$$0.status<300||xhr$$0.status===304?"success":"error";if(status==="success"){if(s$$0.success)s$$0.success.call(s$$0.context,
data,"success",xhr$$0);deferred.resolve(xhr$$0.responseText,"success",xhr$$0);if(g)$.event.trigger("ajaxSuccess",[xhr$$0,s$$0])}else if(status){if(errMsg===undefined)errMsg=xhr$$0.statusText;if(s$$0.error)s$$0.error.call(s$$0.context,xhr$$0,status,errMsg);deferred.reject(xhr$$0,"error",errMsg);if(g)$.event.trigger("ajaxError",[xhr$$0,s$$0,errMsg])}if(g)$.event.trigger("ajaxComplete",[xhr$$0,s$$0]);if(g&&!--$.active)$.event.trigger("ajaxStop");if(s$$0.complete)s$$0.complete.call(s$$0.context,xhr$$0,
status);callbackProcessed=true;if(s$$0.timeout)clearTimeout(timeoutHandle);setTimeout(function(){if(!s$$0.iframeTarget)$io.remove();else $io.attr("src",s$$0.iframeSrc);xhr$$0.responseXML=null},100)}var form=$form[0];var el;var i;var s$$0;var g;var id;var $io;var io;var xhr$$0;var sub;var n;var timedOut;var timeoutHandle;var deferred=$.Deferred();deferred.abort=function(status){xhr$$0.abort(status)};if(a$$0)for(i=0;i<elements.length;i++){el=$(elements[i]);if(hasProp)el.prop("disabled",false);else el.removeAttr("disabled")}s$$0=
$.extend(true,{},$.ajaxSettings,options);s$$0.context=s$$0.context||s$$0;id="jqFormIO"+(new Date).getTime();if(s$$0.iframeTarget){$io=$(s$$0.iframeTarget);n=$io.attr2("name");if(!n)$io.attr2("name",id);else id=n}else{$io=$('\x3ciframe name\x3d"'+id+'" src\x3d"'+s$$0.iframeSrc+'" /\x3e');$io.css({position:"absolute",top:"-1000px",left:"-1000px"})}io=$io[0];xhr$$0={aborted:0,responseText:null,responseXML:null,status:0,statusText:"n/a",getAllResponseHeaders:function(){},getResponseHeader:function(){},
setRequestHeader:function(){},abort:function(status){var e=status==="timeout"?"timeout":"aborted";log("aborting upload... "+e);this.aborted=1;try{if(io.contentWindow.document.execCommand)io.contentWindow.document.execCommand("Stop")}catch(ignore){}$io.attr("src",s$$0.iframeSrc);xhr$$0.error=e;if(s$$0.error)s$$0.error.call(s$$0.context,xhr$$0,e,status);if(g)$.event.trigger("ajaxError",[xhr$$0,s$$0,e]);if(s$$0.complete)s$$0.complete.call(s$$0.context,xhr$$0,e)}};g=s$$0.global;if(g&&0===$.active++)$.event.trigger("ajaxStart");
if(g)$.event.trigger("ajaxSend",[xhr$$0,s$$0]);if(s$$0.beforeSend&&s$$0.beforeSend.call(s$$0.context,xhr$$0,s$$0)===false){if(s$$0.global)$.active--;deferred.reject();return deferred}if(xhr$$0.aborted){deferred.reject();return deferred}sub=form.clk;if(sub){n=sub.name;if(n&&!sub.disabled){s$$0.extraData=s$$0.extraData||{};s$$0.extraData[n]=sub.value;if(sub.type=="image"){s$$0.extraData[n+".x"]=form.clk_x;s$$0.extraData[n+".y"]=form.clk_y}}}var CLIENT_TIMEOUT_ABORT=1;var SERVER_ABORT=2;var csrf_token=
$("meta[name\x3dcsrf-token]").attr("content");var csrf_param=$("meta[name\x3dcsrf-param]").attr("content");if(csrf_param&&csrf_token){s$$0.extraData=s$$0.extraData||{};s$$0.extraData[csrf_param]=csrf_token}if(s$$0.forceSync)doSubmit();else setTimeout(doSubmit,10);var data;var doc;var domCheckCount=50;var callbackProcessed;var toXml=$.parseXML||function(s,doc){if(window.ActiveXObject){doc=new ActiveXObject("Microsoft.XMLDOM");doc.async="false";doc.loadXML(s)}else doc=(new DOMParser).parseFromString(s,
"text/xml");return doc&&doc.documentElement&&doc.documentElement.nodeName!="parsererror"?doc:null};var parseJSON=$.parseJSON||function(s){return window["eval"]("("+s+")")};var httpData=function(xhr,type,s){var ct=xhr.getResponseHeader("content-type")||"";var xml=type==="xml"||!type&&ct.indexOf("xml")>=0;var data=xml?xhr.responseXML:xhr.responseText;if(xml&&data.documentElement.nodeName==="parsererror")if($.error)$.error("parsererror");if(s&&s.dataFilter)data=s.dataFilter(data,type);if(typeof data===
"string")if(type==="json"||!type&&ct.indexOf("json")>=0)data=parseJSON(data);else if(type==="script"||!type&&ct.indexOf("javascript")>=0)$.globalEval(data);return data};return deferred}if(!this.length){log("ajaxSubmit: skipping submit process - no element selected");return this}var method;var action;var url;var $form=this;if(typeof options=="function")options={success:options};else if(options===undefined)options={};method=options.type||this.attr2("method");action=options.url||this.attr2("action");
url=typeof action==="string"?$.trim(action):"";url=url||window.location.href||"";if(url)url=(url.match(/^([^#]+)/)||[])[1];options=$.extend(true,{url:url,success:options.success||$.ajaxSettings.success,type:method||$.ajaxSettings.type,iframeSrc:/^https/i.test(window.location.href||"")?"javascript:false":"about:blank"},options);var veto={};this.trigger("form-pre-serialize",[this,options,veto]);if(veto.veto){log("ajaxSubmit: submit vetoed via form-pre-serialize trigger");return this}if(options.beforeSerialize&&
options.beforeSerialize(this,options)===false){log("ajaxSubmit: submit aborted via beforeSerialize callback");return this}var traditional=options.traditional;if(traditional===undefined)traditional=$.ajaxSettings.traditional;var elements=[];var qx;var a=this.formToArray(options.semantic,elements);if(options.data){options.extraData=options.data;qx=$.param(options.data,traditional)}if(options.beforeSubmit&&options.beforeSubmit(a,this,options)===false){log("ajaxSubmit: submit aborted via beforeSubmit callback");
return this}this.trigger("form-submit-validate",[a,this,options,veto]);if(veto.veto){log("ajaxSubmit: submit vetoed via form-submit-validate trigger");return this}var q=$.param(a,traditional);if(qx)q=q?q+"\x26"+qx:qx;if(options.type.toUpperCase()=="GET"){options.url+=(options.url.indexOf("?")>=0?"\x26":"?")+q;options.data=null}else options.data=q;var callbacks=[];if(options.resetForm)callbacks.push(function(){$form.resetForm()});if(options.clearForm)callbacks.push(function(){$form.clearForm(options.includeHidden)});
if(!options.dataType&&options.target){var oldSuccess=options.success||function(){};callbacks.push(function(data){var fn=options.replaceTarget?"replaceWith":"html";$(options.target)[fn](data).each(oldSuccess,arguments)})}else if(options.success)callbacks.push(options.success);options.success=function(data,status,xhr){var context=options.context||this;var i=0;for(var max=callbacks.length;i<max;i++)callbacks[i].apply(context,[data,status,xhr||$form,$form])};if(options.error){var oldError=options.error;
options.error=function(xhr,status,error){var context=options.context||this;oldError.apply(context,[xhr,status,error,$form])}}if(options.complete){var oldComplete=options.complete;options.complete=function(xhr,status){var context=options.context||this;oldComplete.apply(context,[xhr,status,$form])}}var fileInputs=$("input[type\x3dfile]:enabled",this).filter(function(){return $(this).val()!==""});var hasFileInputs=fileInputs.length>0;var mp="multipart/form-data";var multipart=$form.attr("enctype")==
mp||$form.attr("encoding")==mp;var fileAPI=feature.fileapi&&feature.formdata;log("fileAPI :"+fileAPI);var shouldUseFrame=(hasFileInputs||multipart)&&!fileAPI;var jqxhr;if(options.iframe!==false&&(options.iframe||shouldUseFrame))if(options.closeKeepAlive)$.get(options.closeKeepAlive,function(){jqxhr=fileUploadIframe(a)});else jqxhr=fileUploadIframe(a);else if((hasFileInputs||multipart)&&fileAPI)jqxhr=fileUploadXhr(a);else jqxhr=$.ajax(options);$form.removeData("jqxhr").data("jqxhr",jqxhr);for(var k=
0;k<elements.length;k++)elements[k]=null;this.trigger("form-submit-notify",[this,options]);return this};$.fn.ajaxForm=function(options){options=options||{};options.delegation=options.delegation&&$.isFunction($.fn.on);if(!options.delegation&&this.length===0){var o={s:this.selector,c:this.context};if(!$.isReady&&o.s){log("DOM not ready, queuing ajaxForm");$(function(){$(o.s,o.c).ajaxForm(options)});return this}log("terminating; zero elements found by selector"+($.isReady?"":" (DOM not ready)"));return this}if(options.delegation){$(document).off("submit.form-plugin",
this.selector,doAjaxSubmit).off("click.form-plugin",this.selector,captureSubmittingElement).on("submit.form-plugin",this.selector,options,doAjaxSubmit).on("click.form-plugin",this.selector,options,captureSubmittingElement);return this}return this.ajaxFormUnbind().bind("submit.form-plugin",options,doAjaxSubmit).bind("click.form-plugin",options,captureSubmittingElement)};$.fn.ajaxFormUnbind=function(){return this.unbind("submit.form-plugin click.form-plugin")};$.fn.formToArray=function(semantic,elements){var a=
[];if(this.length===0)return a;var form=this[0];var formId=this.attr("id");var els=semantic?form.getElementsByTagName("*"):form.elements;var els2;if(els&&!/MSIE [678]/.test(navigator.userAgent))els=$(els).get();if(formId){els2=$(":input[form\x3d"+formId+"]").get();if(els2.length)els=(els||[]).concat(els2)}if(!els||!els.length)return a;var i;var j;var n;var v;var el;var max;var jmax;for(i=0,max=els.length;i<max;i++){el=els[i];n=el.name;if(!n||el.disabled)continue;if(semantic&&form.clk&&el.type=="image"){if(form.clk==
el){a.push({name:n,value:$(el).val(),type:el.type});a.push({name:n+".x",value:form.clk_x},{name:n+".y",value:form.clk_y})}continue}v=$.fieldValue(el,true);if(v&&v.constructor==Array){if(elements)elements.push(el);for(j=0,jmax=v.length;j<jmax;j++)a.push({name:n,value:v[j]})}else if(feature.fileapi&&el.type=="file"){if(elements)elements.push(el);var files=el.files;if(files.length)for(j=0;j<files.length;j++)a.push({name:n,value:files[j],type:el.type});else a.push({name:n,value:"",type:el.type})}else if(v!==
null&&typeof v!="undefined"){if(elements)elements.push(el);a.push({name:n,value:v,type:el.type,required:el.required})}}if(!semantic&&form.clk){var $input=$(form.clk);var input=$input[0];n=input.name;if(n&&!input.disabled&&input.type=="image"){a.push({name:n,value:$input.val()});a.push({name:n+".x",value:form.clk_x},{name:n+".y",value:form.clk_y})}}return a};$.fn.formSerialize=function(semantic){return $.param(this.formToArray(semantic))};$.fn.fieldSerialize=function(successful){var a=[];this.each(function(){var n=
this.name;if(!n)return;var v=$.fieldValue(this,successful);if(v&&v.constructor==Array){var i=0;for(var max=v.length;i<max;i++)a.push({name:n,value:v[i]})}else if(v!==null&&typeof v!="undefined")a.push({name:this.name,value:v})});return $.param(a)};$.fn.fieldValue=function(successful){var val=[];var i=0;for(var max=this.length;i<max;i++){var el=this[i];var v=$.fieldValue(el,successful);if(v===null||typeof v=="undefined"||v.constructor==Array&&!v.length)continue;if(v.constructor==Array)$.merge(val,
v);else val.push(v)}return val};$.fieldValue=function(el,successful){var n=el.name;var t=el.type;var tag=el.tagName.toLowerCase();if(successful===undefined)successful=true;if(successful&&(!n||el.disabled||t=="reset"||t=="button"||(t=="checkbox"||t=="radio")&&!el.checked||(t=="submit"||t=="image")&&el.form&&el.form.clk!=el||tag=="select"&&el.selectedIndex==-1))return null;if(tag=="select"){var index=el.selectedIndex;if(index<0)return null;var a=[];var ops=el.options;var one=t=="select-one";var max=
one?index+1:ops.length;for(var i=one?index:0;i<max;i++){var op=ops[i];if(op.selected){var v=op.value;if(!v)v=op.attributes&&op.attributes.value&&!op.attributes.value.specified?op.text:op.value;if(one)return v;a.push(v)}}return a}return $(el).val()};$.fn.clearForm=function(includeHidden){return this.each(function(){$("input,select,textarea",this).clearFields(includeHidden)})};$.fn.clearFields=$.fn.clearInputs=function(includeHidden){var re=/^(?:color|date|datetime|email|month|number|password|range|search|tel|text|time|url|week)$/i;
return this.each(function(){var t=this.type;var tag=this.tagName.toLowerCase();if(re.test(t)||tag=="textarea")this.value="";else if(t=="checkbox"||t=="radio")this.checked=false;else if(tag=="select")this.selectedIndex=-1;else if(t=="file")if(/MSIE/.test(navigator.userAgent))$(this).replaceWith($(this).clone(true));else $(this).val("");else if(includeHidden)if(includeHidden===true&&/hidden/.test(t)||typeof includeHidden=="string"&&$(this).is(includeHidden))this.value=""})};$.fn.resetForm=function(){return this.each(function(){if(typeof this.reset==
"function"||typeof this.reset=="object"&&!this.reset.nodeType)this.reset()})};$.fn.enable=function(b){if(b===undefined)b=true;return this.each(function(){this.disabled=!b})};$.fn.selected=function(select){if(select===undefined)select=true;return this.each(function(){var t=this.type;if(t=="checkbox"||t=="radio")this.checked=select;else if(this.tagName.toLowerCase()=="option"){var $sel=$(this).parent("select");if(select&&$sel[0]&&$sel[0].type=="select-one")$sel.find("option").selected(false);this.selected=
select}})};$.fn.ajaxSubmit.debug=false});
var Abaxx=function(){function Package(props){if(props)jQuery.extend(this,props)}Package.prototype.createPackage=function(packageName){var i;var levels;var currentPackage=this;if(arguments.length>1)for(i=0;i<arguments.length;i++)this.createPackage(arguments[i]);levels=packageName.split(".");for(i=0;i<levels.length;++i){currentPackage[levels[i]]=currentPackage[levels[i]]||new Package;currentPackage=currentPackage[levels[i]]}return currentPackage};Package.prototype.define=function(namespace,init){var thePackage=
this.createPackage(namespace);var scope={};var o=jQuery.isFunction(init)?init.apply(scope):init;jQuery.extend(thePackage,o);thePackage.__internals=scope.internals;if(window.debugDependencies===true)thePackage._init=init};var defaultPortalLanguage="en";var defaultPortalLocale="en_US";var defaultBaseUrl="";var displayType={Param:"$display.type",SinglePart:"single-part",SinglePartWithDecorator:"single-part-decorator"};document.cookie="javascript\x3denabled;path\x3d/";var root=new Package({baseUrl:defaultBaseUrl,
portalLanguage:defaultPortalLanguage,portalLocale:defaultPortalLocale,displayType:displayType,init:function(language,locale,theBaseUrl){try{this.baseUrl=theBaseUrl;this.portalLocale=locale;this.portalLanguage=language;window.CKEDITOR_BASEPATH=this.baseUrl+"scripts/ckeditor/"}catch(t){}},toString:function(){return"baseUrl: "+this.baseUrl+", portalLanguage: "+this.portalLanguage+", portalLocale: "+this.portalLocale}});root.createPackage("util","layout","table","href","tree","switchlayout","decorator",
"collaboration");return root}();
Abaxx.define("core",function(){function _handleOnChangeSubmit(event){var $this=jQuery(this);var abxEvent=jQuery(event.target).data("abxOnChangeSubmit");$this.submitAbaxxEvent(abxEvent)}function _handleConfirm(event){var message=(jQuery(this).data("abxConfirm")||"").replace(/\\n/g,"\n");if(!confirm(message)){event.stopImmediatePropagation();event.stopPropagation();event.preventDefault()}}function unescapeHtml(s,keepScripts){var unescaped=jQuery("\x3cdiv /\x3e").html(s).text();if(!keepScripts)unescaped=
unescaped.replace(/<script.*>.*<\/script>/g,"");return unescaped}function companionScript(name,script){var dataKey=name.replace(/^data-/,"");onReady(function(){jQuery("["+name+"]").each(function(index,element){var $element=jQuery(element);if(!$element.data(dataKey+"-initialized")){$element.data(dataKey+"-initialized",true);script($element,$element.data(dataKey.toLowerCase()))}})})}var readyListeners=[];var initialDomReady=false;var location=document.location;var onReady=function addReadyListener(listener){for(var i=
0;i<readyListeners.length;i++)if(readyListeners[i]===listener)return;if(initialDomReady)listener();readyListeners.push(listener)};var triggerReadyEvent=function triggerReadyEvent(){initialDomReady=true;for(var i=0;i<readyListeners.length;i++)try{readyListeners[i]()}catch(e){if(window.console&&console.error)console.error(e)}jQuery(document).trigger(jQuery.Event("abx_page_ready"))};var setUrlParameter=function(url,name,value){if(!name)return url;if(arguments.length===2){if(jQuery.isPlainObject(name)){var map=
name;jQuery.each(map,function(key,value){if(map.hasOwnProperty(key))url=setUrlParameter(url,key,value)});return url}var decoded=/^([^=]+)=([^=]+)$/.exec(name);if(decoded)return setUrlParameter(url,decoded[1],decoded[2])}var rUrlWithOptionalAnchor=/(^[^#]*)(#.*)?$/;var result;var encodedNameAndValue=encodeURIComponent(name)+"\x3d"+encodeURIComponent(value);var nameOrEncodedName="(?:"+name.replace("$","\\$")+"|"+encodeURIComponent(name)+")";var rName=new RegExp("(\\?|\x26|^)("+nameOrEncodedName+"\x3d[^$\x26]*)($|\x26)");
url=(rUrlWithOptionalAnchor.exec(url)||["",""])[1];var anchor=RegExp.$2||"";if(rName.test(url))result=url.replace(rName,"$1"+encodedNameAndValue+"$3");else if(url==="")result=encodedNameAndValue;else if(url.indexOf("?")!==-1||url.indexOf("\x3d")!==-1&&url.indexOf(";")===-1)result=url+"\x26"+encodedNameAndValue;else result=url+"?"+encodedNameAndValue;return result+anchor};var setParameter=function(form,name,value){form=jQuery(form);if(form.find("input[name\x3d'"+name+"']").length===0)jQuery("\x3cinput type\x3d'hidden' /\x3e").attr({name:name,
value:value}).appendTo(form);else form.find("input[name\x3d'"+name+"']").val(value)};var _resolveFormFromObjectOrId=function(formname){var form;if(formname===null||formname===undefined)form=null;else if(typeof formname==="string")form=document.getElementById(formname);else form=formname;return form};var OpenPopupEvent=function(data){return jQuery.Event("abx_open_popup",data)};var ClosePopupEvent=function(data){return jQuery.Event("abx_close_popup",data)};var OpenLinkEvent=function(data){return jQuery.Event("abx_open_link",
data)};var submitForm=function(idOrForm,popupMode,originalEventName){var form;var popupEvent;form=_resolveFormFromObjectOrId(idOrForm);if(typeof form.onsubmit==="function"&&!form.onsubmit())return false;if(popupMode===true||popupMode==="open")popupEvent=new OpenPopupEvent({form:form,originalEventName:originalEventName});else if(popupMode==="close"||popupMode==="only-close")popupEvent=new ClosePopupEvent({form:form,originalEventName:originalEventName,popupMode:popupMode});if(popupEvent){jQuery(form).trigger(popupEvent);
if(popupEvent.isDefaultPrevented())return false}jQuery(form).submit();return false};var submitEvent=function(formname,event,ignored,popupMode,button){var form=_resolveFormFromObjectOrId(formname);if(form===null&&typeof button!=="undefined")form=button.form;var originalEventName=jQuery(form).find("input[name\x3d'$event']").val()||"";setParameter(form,"$event",event);return submitForm(form,popupMode,originalEventName)};var sendEvent=function(eventUrl,button,popupMode){var popupEvent;if(popupMode===
true||popupMode==="open")popupEvent=new OpenPopupEvent({url:eventUrl});else if(popupMode==="close"||popupMode==="only-close")popupEvent=new ClosePopupEvent({url:eventUrl,popupMode:popupMode});if(popupEvent){jQuery(button||document).trigger(popupEvent);if(popupEvent.isDefaultPrevented())return}var linkEvent=new OpenLinkEvent({url:eventUrl});jQuery(button).trigger(linkEvent)};var scrollToAnchor=function(url){var anchor=url.indexOf("#")>=0?url.substring(url.indexOf("#")+1):null;if(anchor!==null){var $anchorElement=
jQuery("a[name\x3d'"+anchor+"']");if($anchorElement.length===0)return;var $scrollingParent=$anchorElement.parents("div").filter(function(){var $div=jQuery(this);return $div.css("overflowX")==="auto"||$div.css("overflowY")==="auto"||$div.css("overflowX")==="scroll"||$div.css("overflowY")==="scroll"}).first();var anchorOffset=$anchorElement.offset();if($scrollingParent.length===0)jQuery(document).scrollTop(anchorOffset.top).scrollLeft(anchorOffset.left);else{var parentOffset=$scrollingParent.offset()||
{top:0,left:0};$scrollingParent.scrollLeft(anchorOffset.left-parentOffset.left).scrollTop(anchorOffset.top-parentOffset.top)}}};var currentZIndex=function(){return Math.max.apply(null,jQuery("*").map(function(index,element){var cssZIndex=jQuery(element).css("z-index");if(cssZIndex==="auto")return 0;try{return parseInt(cssZIndex,10)}catch(e){return 0}}).get())};var registeredZIndexes=[10];var nextZIndex=function(offset){offset=offset||1;var nextIndex=Math.max.apply(null,registeredZIndexes)+offset;
registeredZIndexes.push(nextIndex);return nextIndex};var freeZIndex=function(zIndex){var i;for(i=0;i<registeredZIndexes.length;i++)if(registeredZIndexes[i]===zIndex)registeredZIndexes.splice(i,1);if(registeredZIndexes.length===0)registeredZIndexes.push(0)};var openWindow=function(url,name,args){var w=args.width||333;var h=args.height||444;var x=(screen.availWidth-w)/2;var y=(screen.availHeight-h)/2;var features="resizable"+",left\x3d"+x+",top\x3d"+y+",width\x3d"+w+",height\x3d"+h;if(args.features)features+=
","+args.features;var popup=window.open(url,name,features);popup.focus();return popup};var establishDefaultBehaviourForButtons=function(){jQuery("button[type\x3dbutton][onclick]").each(function(index,button){if(!button.abxOriginalOnClick){button.abxOriginalOnClick=button.onclick;button.onclick=function(event){var result=button.abxOriginalOnClick(event||window.event);if(!result)jQuery.Event(event||window.event).preventDefault();return result}}})};var enhanceForms=function(){jQuery("form").each(function(index,
form){var $form=jQuery(form);var popupMode=$form.attr("data-xpopup-mode");var id=$form.attr("id");if(typeof popupMode==="undefined")popupMode="auto";if(typeof form._event==="undefined")form._event=function(event,doSubmit){return submitEvent(form,event,doSubmit,popupMode)}});establishDefaultBehaviourForButtons()};var _handleButtonClick=function(event){var $button;var $form;var popupMode;var abaxxEvent;var url;$button=jQuery(this);if(!event.isDefaultPrevented()){$form=$button.parents("form").first();
if($form.length==0){var formId=$button.parents("[data-abx-submitform]").attr("data-abx-submitform");if(formId!=null)$form=jQuery("form[id\x3d'"+formId+"']")}var params=$button.data("abxParams");if(params!=null&&$form.length>0)jQuery.each(params,function(key,values){jQuery.each(values,function(index,value){setParameter($form,key,value)})});popupMode=$button.attr("data-xpopupmode")||"auto";if($button.attr("data-xhref")||$form.length===0){url=$button.attr("href")||$button.attr("data-xhref");sendEvent(url,
this,popupMode)}else{abaxxEvent=$button.attr("data-xevent");submitEvent($form.attr("id"),abaxxEvent,true,popupMode,this)}event.preventDefault()}};var _handleButtonPopupClick=function(event){var $form;var $button=jQuery(this);var popupMode=$button.attr("data-xpopupmode")||"auto";if(!event.isDefaultPrevented()||popupMode==="auto"){$form=$button.parents("form").first();if($form.length>0){submitEvent($form,null,true,popupMode,this);event.preventDefault()}}};var _handleHrefWithPopupModeOpen=function(clickEvent){var $a=
jQuery(this);if(!clickEvent.isDefaultPrevented()){var popupEvent=new Abaxx.core.OpenPopupEvent({url:$a.attr("href")});$a.trigger(popupEvent);if(popupEvent.isDefaultPrevented())clickEvent.preventDefault()}};var _handleHrefWithPopupModeClose=function(clickEvent){var $a=jQuery(this);if(!clickEvent.isDefaultPrevented()){var popupEvent=new Abaxx.core.ClosePopupEvent({url:$a.attr("href")});$a.trigger(popupEvent);if(popupEvent.isDefaultPrevented())clickEvent.preventDefault()}};var _openLink=function(event){if(!event.isDefaultPrevented()){event.preventDefault();
if(Abaxx.loadingIndicator)Abaxx.loadingIndicator.show();location.assign(event.url);if(Abaxx.loadingIndicator)Abaxx.loadingIndicator.remove()}};jQuery.fn.submitAbaxxEvent=function(eventName){var form=this.filter("form")[0];var elementsWithForm;if(!form){elementsWithForm=this.filter(function(){return typeof this.form!=="undefined"});if(elementsWithForm.length>0)form=elementsWithForm[0].form;else form=this.closest("form")[0]}if(form)if(eventName)submitEvent(form,eventName);else submitForm(form);return this};
var registerEventHandlers=function(){jQuery(document).off(".abaxx_core").on("click.abaxx_core","input[type\x3dsubmit][data-xevent], input[type\x3dimage][data-xevent], button[data-xevent], a[data-xevent]",_handleButtonClick).on("click.abaxx_core","input[type\x3dsubmit][data-xpopupmode]:not([data-xevent]), input[type\x3dimage][data-xpopupmode]:not([data-xevent])",_handleButtonPopupClick).on("click.abaxx_core","a[data-xpopupmode\x3dopen]",_handleHrefWithPopupModeOpen).on("click.abaxx_core","a[data-xpopupmode\x3dclose]",
_handleHrefWithPopupModeClose).on("change.abaxx_core","[data-abx-on-change-submit]",_handleOnChangeSubmit).on("abx_open_link.abaxx_core",_openLink);onReady(function(){jQuery("[data-abx-confirm]").off("click.abaxx_core").on("click.abaxx_core",_handleConfirm)})};var cloneAndReplace=function(source,targetId,idSuffix){idSuffix=idSuffix||"Bottom";var $target=jQuery("[id\x3d'"+targetId+"']");var $clone=jQuery(source).clone();$clone.find("*[id]").attr("id",function(index,id){return id+idSuffix});$clone.attr("id",
targetId);$clone.addClass("abaxx-pos-bottom");$clone.removeClass("abaxx-pos-top");$target.replaceWith($clone)};var cloneFragments=function(){jQuery("div[data-abx-clone]").each(function(index,fragment){var $fragment=jQuery(fragment);var target=$fragment.attr("id");if(typeof target==="undefined")return;cloneAndReplace(fragment,target+"Bottom")})};var initInfo=jQuery("[data-abx-web-context]");if(initInfo.length>0)Abaxx.init(initInfo.data("abxWebLanguage"),initInfo.data("abxWebLocale"),initInfo.data("abxWebContext"));
jQuery(triggerReadyEvent);jQuery(cloneFragments);registerEventHandlers();onReady(enhanceForms);companionScript("data-abx-core-open-window",function(trigger,data){if(data)jQuery(trigger).click(function(evt){evt.preventDefault();openWindow(data.url,data.name,data)})});this.internals={clearReadyListeners:function(){readyListeners=[]},removeReadyListener:function(listener){for(var i=0;i<readyListeners.length;i++)if(readyListeners[i]===listener){readyListeners.splice(i,1);return}},setLocationService:function(service){location=
service}};(function(){var matched;var browser;jQuery.uaMatch=function(ua){ua=ua.toLowerCase();var match=/(chrome)[ \/]([\w.]+)/.exec(ua)||/(webkit)[ \/]([\w.]+)/.exec(ua)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(ua)||/(msie) ([\w.]+)/.exec(ua)||ua.indexOf("compatible")<0&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(ua)||[];return{browser:match[1]||"",version:match[2]||"0"}};matched=jQuery.uaMatch(navigator.userAgent);browser={};if(matched.browser){browser[matched.browser]=true;browser.version=matched.version}if(browser.chrome)browser.webkit=
true;else if(browser.webkit)browser.safari=true;jQuery.browser=browser})();return{OpenPopupEvent:OpenPopupEvent,ClosePopupEvent:ClosePopupEvent,OpenLinkEvent:OpenLinkEvent,setParameter:setParameter,setUrlParameter:setUrlParameter,submitForm:submitForm,sendEvent:sendEvent,submitEvent:submitEvent,scrollToAnchor:scrollToAnchor,currentZIndex:currentZIndex,nextZIndex:nextZIndex,freeZIndex:freeZIndex,openWindow:openWindow,enhanceForms:enhanceForms,registerEventHandlers:registerEventHandlers,cloneAndReplace:cloneAndReplace,
onReady:onReady,triggerReadyEvent:triggerReadyEvent,companionScript:companionScript,unescapeHtml:unescapeHtml}});
Abaxx.define("i18n",function(){function Amount(value,currency){if(value instanceof Amount){this.value=value.value;this.currency=value.currency}else if(typeof value==="object"&&typeof value.value!=="undefined"){this.value=Number(value.value);if(typeof value.currency==="string")this.currency=value.currency;else if(typeof value.cur==="string")this.currency=value.cur}else{this.value=Number(value);this.currency=currency}}function parseAmount(text){var normalized;var result;if(typeof text==="number")return text;
if(Abaxx.portalLocale.indexOf("de")===0)normalized=text.replace(/\./g,"").replace(/,/g,".");else normalized=text.replace(/,/g,"");result=Number(normalized);if(isNaN(result))result=0;return result}function formatAmount(amountOrNumber,fractionDigits){var amount=new Amount(amountOrNumber);return formatNumberWithSymbol(amount.value,amount.currency?" "+amount.currency:"",fractionDigits)}function absoluteAmount(amountOrNumber){var amount=new Amount(amountOrNumber);return amount.abs()}function formatPercent(percent,
fractionDigits){var symbol=" %";return formatNumberWithSymbol(percent,symbol,fractionDigits)}function formatNumberWithSymbol(number,symbol,fractionDigits){if(fractionDigits===undefined)fractionDigits=2;if(symbol===undefined)symbol="";if(typeof Intl!=="undefined"&&Intl.NumberFormat)return Intl.NumberFormat(Abaxx.portalLocale.replace(/_/g,"-"),{minimumFractionDigits:fractionDigits,maximumFractionDigits:fractionDigits}).format(number)+symbol;var thousandsSeparator=",";var decimalSeparator=".";var text=
number.toFixed(fractionDigits).replace(/,/g,"");var integerText=text.split(".")[0]||"0";var fractionsText=text.split(".")[1]||"0";if(Abaxx.portalLocale.indexOf("de")===0){thousandsSeparator=".";decimalSeparator=","}integerText=integerText.replace(/\B(?=(\d{3})+(?!\d))/g,thousandsSeparator);if(fractionDigits===0)return integerText;return integerText+decimalSeparator+fractionsText+symbol}Amount.prototype.format=function(fractionDigits){return formatNumberWithSymbol(this.value,this.currency?" "+this.currency:
"",fractionDigits)};Amount.prototype.abs=function(){return new Amount(Math.abs(this.value),this.currency)};return{Amount:Amount,parseAmount:parseAmount,absoluteAmount:absoluteAmount,formatAmount:formatAmount,formatPercent:formatPercent}});
Abaxx.define("device",function(){function isSmallScreen(){if(typeof is_small_and_down=="function")return is_small_and_down();console.log("is_small_and_down() not found");return false}function isMediumScreen(){if(typeof is_medium_and_down=="function")return is_medium_and_down();console.log("is_medium_and_down() not found");return false}function isLargeScreen(){if(typeof is_large_up=="function")return is_large_up();console.log("is_large_up() not found");return false}function isScreen(size){if(window.Foundation&&
Foundation.media_queries[size])return matchMedia(mediaQueries[size]).matches}function isAndroid(){var nua=navigator.userAgent;return nua.indexOf("Android ")>-1}function isIeMobile(userAgent){var ieMobileRE=/IEMobile\/(\d+)(\.\d+)?/;return ieMobileRE.test(userAgent)}function isTouch(){return"ontouchstart"in document.documentElement}function isIOS(){var nua=navigator.userAgent;return/\((iPhone|iPad|iPod touch);.*\)/.exec(nua)!==null}var defaultMediaQueries={small:"only screen",medium:"only screen and (min-width: 641px)",
large:"only screen and (min-width: 1025px)"};var mediaQueries=jQuery.extend(defaultMediaQueries,window.Foundation?window.Foundation.media_queries:{});if(isIeMobile(navigator.userAgent))jQuery("html").addClass("ie-mobile");return{isSmallScreen:isSmallScreen,isMediumScreen:isMediumScreen,isLargeScreen:isLargeScreen,isScreen:isScreen,isAndroid:isAndroid,isIOS:isIOS,isTouch:isTouch}});
Abaxx.define("log",function(){function determineLogMethod(name,fallback){if(typeof console!=="undefined")if(jQuery.isFunction(console[name]))return function(){console[name].apply(console,arguments)};else if(typeof console[name]==="object"){if(isIEObjectConsole)return console[name];try{console[name]("Initializing Abaxx.log");isIEObjectConsole=true;return console[name]}catch(e){return fallback}}return fallback}var exports={};var isIEObjectConsole=false;exports.log=determineLogMethod("log",function(){});
exports.debug=determineLogMethod("debug",exports.log);exports.info=determineLogMethod("info",exports.log);exports.error=determineLogMethod("error",exports.log);return exports});
Abaxx.define("loadingIndicator",function(){var LoadingIndicator=function(indicatorId,position){var TYPE_AJAX="ajax";var TYPE_PAGE="page";var currentType;var invocationCount=0;position=position||"body";var loadingIndicator={show:function(type){type=type||TYPE_AJAX;if(jQuery("#"+indicatorId).length===0)jQuery(position).append("\x3cdiv id\x3d'"+indicatorId+"'\x3eLoading...\x3c/div\x3e");if(currentType!==TYPE_PAGE){currentType=type;invocationCount+=1}},fullPageLoad:function(){loadingIndicator.show(TYPE_PAGE)},
remove:function(){if(currentType!==TYPE_PAGE){jQuery("#"+indicatorId).remove();currentType=null;invocationCount=0}},removeOneLevel:function(){invocationCount-=1;if(invocationCount<=0){invocationCount=0;this.remove()}},getMessage:function(){return jQuery("#"+indicatorId).text()},setMessage:function(message){jQuery("#"+indicatorId).text(message)},isDisplayed:function(){return jQuery("#"+indicatorId).length>0},Type:{page:TYPE_PAGE,ajax:TYPE_AJAX}};if(window.Ajax&&Ajax.Responders)Ajax.Responders.register({onCreate:function(){loadingIndicator.show()},
onComplete:function(){loadingIndicator.remove()},on404:function(){loadingIndicator.remove()},onFailure:function(){loadingIndicator.remove()},onException:function(){loadingIndicator.remove()}});jQuery(document).ajaxSend(function(event,xhr,options){if(!options||!options.omitLoadingIndicator)loadingIndicator.show()});jQuery(document).ajaxComplete(function(){loadingIndicator.removeOneLevel()});jQuery(document).ajaxStop(function(){loadingIndicator.remove()});jQuery(document).on("abx_page_ready",function(){loadingIndicator.remove()});
return loadingIndicator};return new LoadingIndicator("systemWorking")});
Abaxx.define("ajax",function(){function getJSON(url,data,options){data=data||{};options=options||{};if(outstandingAjaxRequests[url]&&typeof outstandingAjaxRequests[url].abort==="function")outstandingAjaxRequests[url].abort();data[Abaxx.displayType.Param]=Abaxx.displayType.SinglePart;options.url=url;options.dataType="json";options.data=data;options.method="POST";outstandingAjaxRequests[url]=jQuery.ajax(options).always(function(){outstandingAjaxRequests[url]=null});return outstandingAjaxRequests[url]}
function isStylesheetLoaded(href,type,media){var url=rUrlWithOptionalPathParameter.exec(href)[1];var existenceCheck="link[rel\x3dstylesheet][href*\x3d'"+url+"']";if(media)existenceCheck+="[media\x3d'"+media+"']";else existenceCheck+=":not([media])";if(type)existenceCheck+="[type\x3d'"+type+"']";else existenceCheck+=":not([type])";return jQuery(existenceCheck).length>0}function insertStylesheets($stylesheets){if(!$stylesheets)return;var $head=jQuery("head");$stylesheets.each(function(index,link){var $link=
jQuery(link);if(!isStylesheetLoaded($link.attr("href"),$link.attr("type"),$link.attr("media")))$head.append(link)})}function isScriptLoaded(scriptUrl){var rawUrl=rUrlWithOptionalPathParameter.exec(scriptUrl)[1];return jQuery("script[src*\x3d'"+rawUrl+"'], script[data-abx-src*\x3d'"+rawUrl+"']").length>0}function includeExternalScript(scriptUrl,defer){if(!isScriptLoaded(scriptUrl)){jQuery.ajax(scriptUrl,{dataType:"script",async:defer,cache:true});var script=document.createElement("script");script.setAttribute("data-abx-src",
scriptUrl);document.getElementsByTagName("head")[0].appendChild(script)}}function _handleInvalidatedParts(event){var partPathsWithUrls;var index;var pathAndUrl;var partSelector;if(event.request&&event.request.getResponseHeader("x-abx-invalidate-parts")){partPathsWithUrls=event.request.getResponseHeader("x-abx-invalidate-parts").split(";");for(index=0;index<partPathsWithUrls.length;index++){pathAndUrl=partPathsWithUrls[index].split(":");partSelector="[data-abx-web-part\x3d'"+pathAndUrl[0]+"']";if(jQuery(partSelector).length>
0)partialLoad(partSelector,decodeURIComponent(pathAndUrl[1]),{triggerEvents:false}).done(triggerPartialLoadEvent)}}}function _handleOnChangePartialSubmit(event){var $element=jQuery(event.target);var $form=$element.closest("form");var abxSubmitOptions=$element.data("abxOnChangePartialSubmit")||{};var options={reloadScripts:true};var eventName=abxSubmitOptions.event;var originalEventName=$form.find("input[name\x3d'$event']").val()||"";if(abxSubmitOptions.partial||typeof abxSubmitOptions.partial==="undefined")if(abxSubmitOptions.replacementSelector)options.replacementSelector=
abxSubmitOptions.replacementSelector;if(eventName)Abaxx.core.setParameter($form,"$event",eventName);var currentFocus=jQuery(document.activeElement);partialSubmit($form,options).always(function(){Abaxx.core.setParameter($form,"$event",originalEventName);if(currentFocus.attr("id")!=null)jQuery("[id\x3d'"+currentFocus.attr("id")+"']").focus()})}function loadAsyncParts(){var asyncLoad=jQuery("[data-abx-load-async]");var updateInfo=[];asyncLoad.each(function(index,container){var element=jQuery(container);
var url=element.attr("data-abx-load-async");element.removeAttr("data-abx-load-async");var reloadId=element.attr("id");if(url&&reloadId)updateInfo.push({url:url,reloadId:reloadId})});jQuery(updateInfo).each(function(index,info){var url=info.url;var reloadId=info.reloadId;var reloadSelector="[id\x3d'"+reloadId+"']";partialLoad(reloadSelector,url,{omitLoadingIndicator:true}).done(function(){jQuery(reloadSelector).removeClass("abx-web-async-loading")})})}var rUrlWithOptionalAnchor=/^([^#]*)(?:#([^#]*))?$/;
var rUrlWithOptionalPathParameter=/^(.*?)(;.*)?$/;var NOP=function(){};var triggerPartialLoadFailedEvent=function(data){jQuery(document).trigger(jQuery.Event("abx_partial_load_failed",data))};var triggerPartialLoadEvent=function(source,data){var $eventSource=source||{};var eventData=data||{};if(!source||jQuery.isPlainObject(source)){$eventSource=jQuery(document);eventData=source}$eventSource.trigger(jQuery.Event("abx_partial_load",eventData))};var triggerHtmlChangedEvent=function(data){jQuery(document).trigger(new jQuery.Event("abx_ajax_html_changed",
data))};var outstandingAjaxRequests={};var urlForSinglePart=function(url,includeDecorator){includeDecorator=includeDecorator===true;url=rUrlWithOptionalAnchor.exec(url||"")[1];var displayType=includeDecorator?Abaxx.displayType.SinglePartWithDecorator:Abaxx.displayType.SinglePart;return Abaxx.core.setUrlParameter(url,Abaxx.displayType.Param,displayType)};var createAjaxSubmitEvent=function(){return jQuery.Event("abx_ajax_submit")};var replaceMatching=function(elementSelector,html,reloadScripts,fireHtmlChangedEvent){var deferred=
new jQuery.Deferred;var newElements=jQuery(elementSelector,html.scriptless);if(newElements.length===0)newElements=jQuery(html.scriptless).filter(elementSelector);if(newElements.length===0)deferred.reject("Element not found: "+elementSelector);else try{var replaced=[];if(newElements.length===1&&jQuery(elementSelector).length===1){jQuery(elementSelector).replaceWith(newElements);replaced.push(elementSelector)}else newElements.each(function(index,element){var id=jQuery(element).attr("id");var idSelector;
if(id){idSelector="[id\x3d'"+id+"']";jQuery(idSelector).replaceWith(element);replaced.push(idSelector)}});if(replaced.length>0)replaced=jQuery(replaced.join(","));insertStylesheets(html.stylesheets);if(typeof reloadScripts==="undefined"||reloadScripts)if(!executeScripts(html.scripts))deferred.reject();if(typeof fireHtmlChangedEvent==="undefined"||fireHtmlChangedEvent)triggerHtmlChangedEvent({changed:replaced});if(deferred.state()!=="rejected")deferred.resolve()}catch(e){deferred.reject(e)}return deferred.promise()};
var partialLoad=function(elementSelector,url,options){var defaultOptions={reloadScripts:true,async:true,data:"",method:"get",success:NOP,transformHtml:NOP,triggerEvents:true,includeDecorator:false};var deferred=jQuery.Deferred();options=jQuery.extend(defaultOptions,options||{});jQuery.ajax(Abaxx.ajax.urlForSinglePart(url,options.includeDecorator),{dataType:"text",async:options.async,data:options.data,type:options.method,success:function(data,status,request){handlePartialLoadSuccess(deferred,url,elementSelector,
options,data,status,request)},error:function(request,status,error){if(options.triggerEvents)triggerPartialLoadFailedEvent({request:request,url:url,cause:status});deferred.reject()}});return deferred.promise()};var handlePartialLoadSuccess=function(deferred,url,elementSelector,options,data,status,request){var contentDisposition=request.getResponseHeader("Content-Disposition");if(contentDisposition!=null&&contentDisposition.indexOf("attachment")>=0){Abaxx.log.log("Ajax download detected, reloading file by browser");
document.location=url;return}var response=parseHtml(data);if(response.redirectUrl)partialLoad(elementSelector,response.redirectUrl,options).done(function(xhr){deferred.resolve(xhr,response.redirectUrl)}).fail(function(){deferred.reject()});else{options.transformHtml(response);replaceMatching(elementSelector,response,options.reloadScripts).fail(function(cause){if(options.triggerEvents)triggerPartialLoadFailedEvent({request:request,url:url,cause:cause});deferred.reject()}).done(function(){deferred.resolve(request,
url);options.success();Abaxx.core.scrollToAnchor(url)}).done(function(){if(options.triggerEvents)triggerPartialLoadEvent({request:request,url:url})})}};var partialSubmit=function(form,options){var $form=jQuery(form);var defaultOptions={replacementSelector:"#"+$form.attr("id"),url:$form[0].action,transformHtml:NOP,success:NOP};options=jQuery.extend(defaultOptions,options||{});options.url=Abaxx.ajax.urlForSinglePart(options.url,options.includeDecorator);var isMultiPart=$form.attr("enctype")==="multipart/form-data";
var deferred=new jQuery.Deferred;var sendResult=sendForm($form,isMultiPart,function(response,text,status){handlePartialLoadSuccess(deferred,options.url,options.replacementSelector,options,text,status,response)},options);if(sendResult.state()==="rejected")return sendResult;else return deferred};var loadSinglePart=function(elementId,url,reloadScripts,asynchronous){partialLoad("[id\x3d'"+elementId+"']",url,{reloadScripts:typeof reloadScripts==="undefined"?true:reloadScripts,async:typeof asynchronous===
"undefined"?true:asynchronous});return false};var loadSinglePartByClass=function(className,url,options){options=jQuery.extend({reloadScripts:true,async:true},options||{});partialLoad("[class~\x3d'"+className+"']",url,options);return false};var partialReload=function(reloadId,reloadUrl,reloadScripts){partialLoad("[id\x3d'"+reloadId+"']",reloadUrl,{reloadScripts:reloadScripts||false,updateHistory:"href"});return false};var ParsedHtml=function(htmlString){this.empty=htmlString.replace(/^\s+|\s+$/g,"").length===
0;this.redirectUrl=null;this.scripts=[];this.scriptless=null;this._extractScripts(htmlString);this._parse(htmlString);this.stylesheets=jQuery(this.scriptless).find("link[rel\x3dstylesheet][href]").remove();return this};ParsedHtml.prototype._extractScripts=function(htmlString){var parsed=this;this.scripts=jQuery.map(htmlString.match(/<script[^>]*>([\S\s]*?)<\/script>/img)||[],function(match){var script=jQuery(match);var type=script.attr("type")||script.attr("lang")||"text/javascript";if(jQuery.inArray(type,
["text/javascript","javascript","text/jscript","jscript"])!==-1){var text=(/<script[^>]*>([\S\s]*?)<\/script>/im.exec(match)||["",""])[1];var redirectMatch=/document\.location\s*=\s*('|")(.+)\1/m.exec(text);if(redirectMatch){parsed.redirectUrl=redirectMatch[2];text=""}if(script.attr("src"))text="Abaxx.ajax.includeExternalScript('"+script.attr("src")+"',"+(script.attr("defer")=="true")+"); "+text;return text}return""});this.scripts=jQuery.grep(this.scripts,function(s){return s})};ParsedHtml.prototype._parse=
function(htmlString){this.scriptless=jQuery.parseHTML("\x3cdiv\x3e"+htmlString+"\x3c/div\x3e")[0]};var parseHtml=function(htmlString){return new ParsedHtml(htmlString)};var executeScripts=function(scripts){var scriptErrors=false;if(typeof scripts==="string")scripts=[scripts];jQuery.each(scripts,function(index,script){try{jQuery.globalEval(script)}catch(e){Abaxx.log.error(e);scriptErrors=true}});return!scriptErrors};var submitForm=function(bodyId,options){options=jQuery.extend({onSuccess:NOP,keepDecorator:false},
options||{});var $part=jQuery("[id\x3d'"+bodyId+"']");var $form=$part.is("form")?$part:$part.find("form").first();var url;var event;if($form.length===0)$form=$part.parents("form").first();if($form.length>0){$form.trigger(createAjaxSubmitEvent());if(options.event){event=$form.find("input[name\x3d'$event']").val()||options.event;Abaxx.core.setParameter($form,"$event",event)}url=$form.attr("action");jQuery.ajax(urlForSinglePart(url,options.keepDecorator),{data:$form.serialize(),dataType:"text",type:"POST",
async:false,success:function(text,status,xhr){options.onSuccess(text,status,xhr)}});return true}return false};var getResponseHeader=function(response,headerName,decodeBase64){decodeBase64=decodeBase64===true;try{var result;if(typeof response.getHeader==="undefined")if(typeof response.getResponseHeader==="undefined")return null;else if(typeof response.getResponseHeader==="function")result=response.getResponseHeader(headerName);else{if(typeof response.getResponseHeader==="object")result=response.getResponseHeader[headerName]}else{result=
response.getHeader(headerName);if(typeof response.getHeader==="function")result=response.getHeader(headerName);else if(typeof response.getHeader==="object")result=response.getHeader[headerName]}if(typeof result!=="undefined"&&result!==null&&result!=="")return decodeBase64?Base64.decode(result):result;else return null}catch(e){return null}};var updateHtmlPageTitle=function(response){try{var htmlTitle=getResponseHeader(response,"HtmlTitle",true);if(htmlTitle!==null)document.title=htmlTitle}catch(e){}};
var enableAsyncAspectValidation=function(){var messageTypes=["error","warning","info"];var getMostSignificantMessages;var showValidationMessages;var validateOnServer;getMostSignificantMessages=function(xml){var i;var messages;var messageToText=function(index,element){return jQuery(element).text()};for(i=0;i<messageTypes.length;i++){messages=jQuery(messageTypes[i],xml);if(messages.length>0)return{type:messageTypes[i],texts:messages.map(messageToText).get()}}return null};showValidationMessages=function(xml){var $validationResult=
jQuery("aspect",xml).first();var messages=getMostSignificantMessages($validationResult);var aspectId=$validationResult.attr("id");var aspectSelector="[id\x3d'"+aspectId+"']";var messageSelector="[id\x3d'"+aspectId+"-message']";var labelSelector="[id\x3d'"+aspectId+"-label']";jQuery(aspectSelector+", "+labelSelector).removeClass("aspect-info aspect-warning aspect-error");if(messages){var tooltip=messages.texts.join("\n");var text$$0=jQuery.map(messages.texts,function(text){return"\x3cspan\x3e"+text+
"\x3c/span\x3e"}).join("");jQuery(messageSelector).html(text$$0).show();jQuery(aspectSelector+", "+labelSelector).addClass("aspect-"+messages.type).attr("title",tooltip);jQuery(labelSelector).css("cursor","help")}else{jQuery(messageSelector).html("").hide();jQuery(aspectSelector+", "+labelSelector).attr("title","");jQuery(labelSelector).css("cursor","")}};validateOnServer=function(event){var $aspect=jQuery(this);jQuery.ajax(Abaxx.baseUrl+"validate",{dataType:"xml",data:{id:$aspect.attr("id"),aspect:$aspect.attr("data-xaspect"),
value:$aspect.val(),part:$aspect.attr("data-xpart")}}).done(showValidationMessages)};jQuery("input[data-xaspect], textarea[data-xaspect]").blur(validateOnServer)};var _handlePartialLoadFailed=function(event){if(event.url)document.location=event.url.replace(/(?:\$|%24)display\.type=single-part(-decorator)?(&?)/g,"")};var _handleActionWithPartialReload=function(clickEvent){var action=jQuery(this);var reloadSelector=action.attr("data-xreload");var reloadScripts=action.attr("data-xreloadscripts");if(!clickEvent.isDefaultPrevented()){clickEvent.preventDefault();
Abaxx.ajax.partialLoad(reloadSelector,action.attr("href"),{reloadScripts:reloadScripts==="true"||false,updateHistory:"href"})}};var _handleActionWithPartialSubmit=function(clickEvent){var action=jQuery(this);var reloadSelector=action.attr("data-xsubmit");var reloadScripts=action.attr("data-xreloadscripts");if(!clickEvent.isDefaultPrevented()){clickEvent.preventDefault();var $form=action.closest("form");if($form.length==0){var formId=action.parents("[data-abx-submitform]").attr("data-abx-submitform");
if(formId!=null)$form=jQuery("form[id\x3d'"+formId+"']")}var params=action.data("abxParams");var oldParams={};if(params!=null&&$form.length>0)jQuery.each(params,function(key,values){oldParams[key]=$form.find("input[name\x3d'"+key+"']").val()||null;jQuery.each(values,function(index,value){Abaxx.core.setParameter($form,key,value)})});var abaxxEvent=action.attr("data-xevent");var originalEventName=$form.find("input[name\x3d'$event']").val()||"";Abaxx.core.setParameter($form,"$event",abaxxEvent);Abaxx.ajax.partialSubmit($form,
{reloadScripts:reloadScripts==="true"||false,replacementSelector:reloadSelector!=="true"?reloadSelector:undefined}).always(function(){Abaxx.core.setParameter($form,"$event",originalEventName);jQuery.each(oldParams,function(key,value){if(value==null)$form.find("input[name\x3d'"+key+"']").remove();else Abaxx.core.setParameter($form,key,value)})})}};var registerEventHandlers=function(){jQuery(document).ajaxComplete(function(event,xhr){updateHtmlPageTitle(xhr)}).off(".abaxx_ajax").on("abx_ajax_html_changed.abaxx_ajax",
Abaxx.core.triggerReadyEvent).on("abx_partial_load_failed.abaxx_ajax",_handlePartialLoadFailed).on("abx_partial_load.abaxx_ajax",_handleInvalidatedParts).on("change.abaxx_ajax","[data-abx-on-change-partial-submit]",_handleOnChangePartialSubmit);jQuery(document.body).on("click.abaxx_ajax","[data-xreload]",_handleActionWithPartialReload).on("click.abaxx_ajax","[data-xsubmit]",_handleActionWithPartialSubmit)};jQuery(registerEventHandlers);Abaxx.core.onReady(enableAsyncAspectValidation);Abaxx.core.onReady(loadAsyncParts);
this.internals={isScriptLoaded:isScriptLoaded,isStylesheetLoaded:isStylesheetLoaded};var sendForm=function(form,isMultiPart,onSuccess,options){var waitInterval=100;var maxWait=500;var timeout=waitInterval*maxWait;var $form=jQuery(form);var deferred=new jQuery.Deferred;var defaultOptions={async:true,method:$form.attr("method")||"POST",url:$form.attr("action"),timeout:timeout,includeDecorator:false};options=jQuery.extend(defaultOptions,options||{});form=$form[0];var submitEvent=createAjaxSubmitEvent();
$form.trigger(submitEvent);if(submitEvent.isDefaultPrevented()){deferred.reject(form);return deferred}Abaxx.loadingIndicator.show();if(isMultiPart){var originalAction=options.url;var originalDisplayType=$form.find("input[name\x3d'"+Abaxx.displayType.Param+"']").val();var uploadFields;uploadFields=$form.find("input[type\x3dfile]").map(function(index,element){return element.name}).get().join(",");var sessionId=(/;.*$/.exec(originalAction)||[""])[0];var part=form.dataset?form.dataset.uploadpart:form.attributes["data-uploadpart"].value;
form.action=Abaxx.baseUrl+"UploadServlet"+sessionId+"?$uploadPart\x3d"+part+"\x26$uploadFields\x3d"+uploadFields;var uploadCompleted=function(transactionId,response){var cleanups=[];var files=[];var newEl;var j;Abaxx.core.setParameter(form,Abaxx.displayType.Param,null);if(response.responseText&&(response.responseText.lastIndexOf("[]",0)===0||response.responseText.lastIndexOf("[{",0)===0)){files=[];try{files=jQuery.parseJSON(response.responseText)}catch(e){Abaxx.log.error("Upload failed",e)}for(j=
0;j<files.length;j++){newEl=jQuery('\x3cinput type\x3d"hidden" /\x3e').attr({name:"$uploadApplet_"+files[j].field,value:files[j].fileName}).appendTo(form);cleanups.push(newEl[0])}}else{Abaxx.log.error("Upload failed",response);jQuery(form).trigger(jQuery.Event("abx_upload_failed"))}newEl=jQuery('\x3cinput type\x3d"hidden" /\x3e').attr({name:"$uploadRequest",value:"true"}).appendTo(form);cleanups.push(newEl);form.action=originalAction;Abaxx.core.setParameter(form,Abaxx.displayType.Param,originalDisplayType);
var cleanupOnSuccess=function(xhr,text,status){jQuery(cleanups).remove();onSuccess(xhr,text,status)};jQuery.ajax(options.url,{data:$form.serialize(),dataType:"text",type:options.method,async:options.async,timeout:options.timeout}).done(function(text,status,xhr){deferred.resolve(form);cleanupOnSuccess(xhr,text,status)}).fail(function(){deferred.reject(form)})};var submitOptions={url:form.action,iframe:true,timeout:options.timeout,success:function(data,status,xhr){uploadCompleted(status,xhr)},error:function(xhr,
status,error){deferred.reject(form)}};jQuery(form).ajaxSubmit(submitOptions)}else jQuery.ajax(options.url,{data:$form.serialize(),dataType:"text",type:options.method,async:options.async,timeout:options.timeout}).done(function(text,status,xhr){try{onSuccess(xhr,text,status)}finally{deferred.resolve(form)}}).fail(function(){Abaxx.core.setParameter(form,Abaxx.displayType.Param,undefined);form.submit();deferred.reject(form)});return deferred.promise()};return{triggerPartialLoadFailedEvent:triggerPartialLoadFailedEvent,
triggerPartialLoadEvent:triggerPartialLoadEvent,triggerHtmlChangedEvent:triggerHtmlChangedEvent,partialSubmit:partialSubmit,partialLoad:partialLoad,getJSON:getJSON,urlForSinglePart:urlForSinglePart,loadSinglePart:loadSinglePart,loadSinglePartByClass:loadSinglePartByClass,partialReload:partialReload,parseHtml:parseHtml,executeScripts:executeScripts,submitForm:submitForm,getResponseHeader:getResponseHeader,updateHtmlPageTitle:updateHtmlPageTitle,createAjaxSubmitEvent:createAjaxSubmitEvent,replaceMatching:replaceMatching,
registerEventHandlers:registerEventHandlers,includeExternalScript:includeExternalScript,insertStylesheets:insertStylesheets,sendForm:sendForm}});
Abaxx.define("popups.adapter",function(){var $template=jQuery('\x3cdiv class\x3d"abaxxPopupPanel" /\x3e');var Popup=function(id,zIndex){this.element=$template.clone().attr("id",id);this.element.dialog({autoOpen:false,modal:true,closeOnEscape:false,position:{my:"center",at:"center",of:window},width:"auto",minHeight:135,zIndex:zIndex,draggable:true,resizable:false,create:function(event){jQuery(event.target).parent().find("\x3e .ui-dialog-titlebar \x3e .ui-dialog-titlebar-close").hide()}});this.element.closest(".ui-dialog").prependTo(document.body);
this.element.parent().find(".ui-dialog-titlebar .ui-dialog-title").addClass("abx-page-icon")};Popup.prototype.open=function open(){if(Abaxx.device.isSmallScreen())window.scrollTo(0,0);var title=jQuery("\x3cspan\x3e"+this.getTitle()+"\x3c/span\x3e");var dialogType=title.find("[data-abx-wdg-dialog-type]");if(dialogType.length>0)this.element.parent().find(".ui-dialog-titlebar .ui-dialog-title").addClass("abx-wdg-"+dialogType.attr("data-abx-wdg-dialog-type"));this.element.dialog("open");if(jQuery.browser.msie){var dialog=
this.element.parent(".ui-dialog");var width=dialog.innerWidth();if(width)dialog.css("width",width)}};Popup.prototype.center=function center(){this.element.dialog({my:"center",at:"center",of:window})};Popup.prototype.setContent=function setContent(newContent){this.element.html(newContent)};Popup.prototype.getContent=function getContent(){return this.element.html()};Popup.prototype.getTitle=function getTitle(){return this.element.dialog("option","title")};Popup.prototype.setTitle=function setTitle(newTitle){this.element.dialog("option",
"title",newTitle)};Popup.prototype.getElement=function getElement(){return this.element};Popup.prototype.close=function closePopup(){this.element.dialog("close");this.setContent("")};Popup.prototype.setDisplayedPart=function setDisplayedPart(partPath){this.partName=partPath.indexOf(".")>0?partPath.substring(partPath.lastIndexOf(".")+1):partPath;this.element.parent().addClass(this.partName)};Popup.prototype.unsetDisplayedPart=function unsetDisplayedPart(partPath){if(this.partName)this.element.parent().removeClass(this.partName)};
Popup.prototype.find=function find(selector){return this.element.find(selector)};Popup.prototype.handleResize=function handleResize(){if(jQuery.browser.msie){var dialog=this.element.parent(".ui-dialog");dialog.css("width","auto");var width=dialog.children(".abaxxPopupPanel").innerWidth();if(width)dialog.css("width",width)}this.center()};Popup.prototype.trigger=function(event){this.element.trigger(event)};return{Popup:Popup}});
Abaxx.define("popups",function(){function triggerPopupCreatedEvent(popup){jQuery(document).trigger(jQuery.Event("abx_popup_created",{popup:popup}))}function triggerPopupOpenedEvent(popup){popup.trigger(new jQuery.Event("abx_popup_opened",{popup:popup}))}function createPopup(){var popup;var zIndex;var nextId;var idPrefix="abaxxPopupPanel_";currentPopup+=1;if(currentPopup===0)jQuery(document.body).addClass("abx-web-hasPopup");nextId=currentPopup;zIndex=Abaxx.core.nextZIndex(1E3);Abaxx.core.nextZIndex(10);
if(typeof popups[currentPopup]==="undefined"||popups[currentPopup]===null){popup=new Abaxx.popups.adapter.Popup(idPrefix+nextId,zIndex);popups[currentPopup]=popup;triggerPopupCreatedEvent(popup)}else popups[currentPopup].getElement().dialog({zIndex:zIndex})}function _handleResize(event){var popup=getPopup(false);if(popup!=null)popup.handleResize()}var displayTypePopup="single-part-popup";var mode={AUTO:"auto",OPEN:"open",CLOSE:"close",CLOSE_WITHOUT_RELOAD:"only-close",SKIP:"skip"};var currentPopup=
-1;var rClosePopup=/&?(%24|\$)closePopup=true/;var popups=[];var popupsToClose=[];var maxRedirect=50;var urlForPopup=function(url){url=/^([^#]*)(?:#([^#]*))?$/.exec(url||"")[1];return Abaxx.core.setUrlParameter(url,Abaxx.displayType.Param,displayTypePopup)};var getPopup=function(newPopup){if(newPopup===true)createPopup();return popups[currentPopup]};var popupIsVisible=function(){return typeof getPopup(false)!=="undefined"};var isElementInPopup=function(element){return popupIsVisible()&&jQuery(element).parents(".abaxxPopupPanel").length>
0};var currentZIndex=function(){var popup=getPopup(false);if(popup)return parseInt(popup.getElement().closest(".ui-dialog").css("z-index"),10);return 0};var closePopup=function(lazy){var popup;if(currentPopup<0)return null;if(currentPopup===0)jQuery(document.body).removeClass("abx-web-hasPopup");popup=getPopup(false);if(popup){removePortletNameFromPopup(popup);popup.trigger(new jQuery.Event("abx_popup_closing"))}if(lazy===true)popupsToClose.push(popups[currentPopup]);else popup.close();currentPopup-=
1;return popups[currentPopup]};var closePopupDelayed=function(){for(;popupsToClose.length>0;){var p=popupsToClose.pop();p.close()}};var fillPopup=function(html,newPopup,basePart){closePopupDelayed();var abaxxPopupPanel=getPopup(newPopup);if(!abaxxPopupPanel)return;abaxxPopupPanel.setContent(html.scriptless);initializeAddPortletNameToPopup(html,abaxxPopupPanel);if(html.title)abaxxPopupPanel.setTitle(html.title);if(basePart)abaxxPopupPanel.setDisplayedPart(basePart);Abaxx.ajax.insertStylesheets(html.stylesheets);
abaxxPopupPanel.open();try{jQuery(".top-bar, [data-topbar]").css("height","").removeClass("expanded")}catch(e){Abaxx.log.error(e)}triggerPopupOpenedEvent(abaxxPopupPanel);abaxxPopupPanel.find("[autofocus]").focus();Abaxx.ajax.executeScripts(html.scripts);Abaxx.ajax.triggerHtmlChangedEvent({changed:abaxxPopupPanel})};var handlePopupResponse=function(html,popupMode,baseComposite){var failed=html.empty;var redirectCount=0;var handleRedirect=function(text,status,response){html=Abaxx.ajax.parseHtml(text);
html.title=Abaxx.ajax.getResponseHeader(response,"Caption",true);baseComposite=Abaxx.ajax.getResponseHeader(response,"BaseComposite");Abaxx.core.scrollToAnchor(this.url);redirectCount=redirectCount+1;failed=redirectCount>maxRedirect};for(var handleRedirectError=function(){failed=true};!failed;){var redirectUrl=html.redirectUrl;if(redirectUrl===null){if(popupMode===mode.CLOSE_WITHOUT_RELOAD)closePopup(false);break}if(rClosePopup.test(redirectUrl)){for(var uri=redirectUrl;rClosePopup.test(uri);)uri=
uri.replace(rClosePopup,"");if(uri.indexOf("?",uri.length-1)!==-1)uri=uri.substring(0,uri.length-1);if(popupMode===mode.CLOSE_WITHOUT_RELOAD){closePopup(false);jQuery.ajax(urlForPopup(uri),{type:"get",dataType:"text",async:true}).done(function(response){Abaxx.ajax.updateHtmlPageTitle(response)});Abaxx.ajax.triggerPartialLoadEvent();return true}else{var parent=closePopup(false);if(typeof parent==="undefined"||parent===null){var linkEvent=new Abaxx.core.OpenLinkEvent({url:uri});jQuery(document).trigger(linkEvent);
return true}}}jQuery.ajax(urlForPopup(redirectUrl),{type:"get",dataType:"text",async:false}).done(handleRedirect).fail(handleRedirectError)}if(!failed&&html.scriptless!==null){if(popupMode!==mode.CLOSE_WITHOUT_RELOAD)fillPopup(html,popupMode===mode.OPEN,baseComposite);Abaxx.ajax.triggerPartialLoadEvent();return true}else return false};var setTitle=function(title){if(title&&popupIsVisible())getPopup(false).setTitle(title)};var openLink=function(url,popupMode){if(popupMode===mode.SKIP)return true;if(popupMode===
mode.CLOSE){var parent=closePopup(true);if(typeof parent==="undefined"||parent===null)return true}var html={title:null};var baseComposite=null;jQuery.ajax(urlForPopup(url),{type:"get",dataType:"text",async:true}).then(function(text,status,xhr){Abaxx.ajax.updateHtmlPageTitle(xhr);html=Abaxx.ajax.parseHtml(text);html.title=Abaxx.ajax.getResponseHeader(xhr,"Caption",true);baseComposite=Abaxx.ajax.getResponseHeader(xhr,"BaseComposite");if(handlePopupResponse(html,popupMode,baseComposite))Abaxx.core.scrollToAnchor(url);
else Abaxx.ajax.triggerPartialLoadFailedEvent({url:url})}).fail(function(){Abaxx.ajax.triggerPartialLoadFailedEvent({url:url})});return false};var _handleSubmitError=function(response,popupMode){var html=Abaxx.ajax.parseHtml(response.responseText);var replacement=jQuery(html.scriptless).find("\x3e div[id], \x3e div[class], \x3e form[id], \x3e form[class]").first();if(replacement.length===1){var toReplace=null;var replacementCandidates;if(replacement.attr("id"))replacementCandidates=jQuery("[id\x3d'"+
replacement.attr("id")+"']");else{var selector=jQuery.trim(jQuery(replacement).attr("class")).replace(/^|\s+/g,".");replacementCandidates=jQuery(selector)}if(replacementCandidates.length===1){toReplace=replacementCandidates.first();toReplace.replaceWith(replacement);Abaxx.ajax.insertStylesheets(html.stylesheets);Abaxx.ajax.executeScripts(html.scripts);Abaxx.ajax.triggerHtmlChangedEvent({changed:toReplace});Abaxx.ajax.triggerPartialLoadEvent();return true}else if(response.status===200){fillPopup(html,
popupMode===mode.OPEN,Abaxx.ajax.getResponseHeader(response,"BaseComposite"));Abaxx.ajax.triggerPartialLoadEvent();return true}}return false};var submitForm=function(formname,popupMode,originalEventName){var $form=typeof formname==="string"?jQuery("[id\x3d'"+formname+"']"):jQuery(formname);if(popupMode===mode.CLOSE){var parent=closePopup(true);if(typeof parent==="undefined"||parent===null){$form.submit();return false}}var isMultiPart=$form.attr("enctype")==="multipart/form-data";var onSuccess=function(response){var actionResult=
Abaxx.ajax.getResponseHeader(response,"ActionResult");if(actionResult==="FAILED"||actionResult&&actionResult.trim&&actionResult.trim()==="FAILED"){if(!_handleSubmitError(response,popupMode)){try{Abaxx.core.setParameter($form,Abaxx.displayType.Param,undefined)}catch(ignored){}$form[0].submit()}return}Abaxx.ajax.updateHtmlPageTitle(response);var html=Abaxx.ajax.parseHtml(response.responseText);var title=Abaxx.ajax.getResponseHeader(response,"Caption",true);var baseComposite=Abaxx.ajax.getResponseHeader(response,
"BaseComposite");if(title!==null)html.title=title;if(!handlePopupResponse(html,popupMode,baseComposite))if(html.redirectUrl){var linkEvent=new Abaxx.core.OpenLinkEvent({url:html.redirectUrl});jQuery(document).trigger(linkEvent)}};Abaxx.core.setParameter($form,Abaxx.displayType.Param,displayTypePopup);return Abaxx.ajax.sendForm($form[0],isMultiPart,onSuccess).always(function(){if(typeof originalEventName!=="undefined")Abaxx.core.setParameter($form,"$event",originalEventName);Abaxx.core.setParameter($form,
Abaxx.displayType.Param,null)})};var needsPopupHandling=function(popupMode){return popupMode===mode.OPEN||popupMode===mode.CLOSE||popupMode===mode.AUTO&&popupIsVisible()};var setMode=function(element,newMode){if(newMode&&mode[newMode.toUpperCase()])jQuery(element).attr("data-xpopupmode",newMode)};var registerEventHandlers=function(){jQuery(document).on("submit","form",function(event){if(!event.isDefaultPrevented()&&popupIsVisible()){event.preventDefault();submitForm(this,mode.AUTO)}}).on("abx_open_popup.popup",
function(event){if(!event.isDefaultPrevented())if(event.form){submitForm(event.form,mode.OPEN,event.originalEventName);event.preventDefault()}else if(event.url)if(!openLink(event.url,mode.OPEN))event.preventDefault()}).on("abx_close_popup.popup",function(event){if(!event.isDefaultPrevented())if(event.form){submitForm(event.form,event.popupMode||mode.CLOSE,event.originalEventName);event.preventDefault()}else if(event.url){if(openLink(event.url,event.popupMode||mode.CLOSE)||event.popupMode===mode.CLOSE_WITHOUT_RELOAD){if(event.popupMode!==
mode.CLOSE_WITHOUT_RELOAD){var linkEvent=new Abaxx.core.OpenLinkEvent({url:event.url});jQuery(event.target).trigger(linkEvent)}event.preventDefault()}}else{closePopup(false);event.preventDefault()}}).on("abx_open_link.popup","body",function(event){if(!event.isDefaultPrevented()&&popupIsVisible()&&!openLink(event.url,mode.AUTO))event.preventDefault()}).on("click","a[href]",function(event){var $a=jQuery(this);var href=$a.attr("href");var popupMode=$a.attr("data-xpopupmode");var target=$a.attr("target");
var isJavaScriptLink=href.toLowerCase().indexOf("javascript:")===0;var targetsAnotherWindow=target&&target!=window.name;var linkEvent;if(!event.isDefaultPrevented()&&popupMode!==mode.SKIP&&!targetsAnotherWindow&&href!==""&&href.indexOf("#")!==0&&popupIsVisible()&&!isJavaScriptLink){linkEvent=jQuery.Event("abx_open_link",{url:$a.attr("href")});$a.trigger(linkEvent);if(linkEvent.isDefaultPrevented())event.preventDefault()}});jQuery.ajaxPrefilter(function(settings){if(popupIsVisible()&&settings.dataType!=
"script")settings.url=Abaxx.core.setUrlParameter(settings.url,Abaxx.displayType.Param,Abaxx.popups.displayType)});if(!Abaxx.device.isAndroid()&&!Abaxx.device.isIOS())jQuery(window).on("resize",function(event){_handleResize(event)});if(screen.orientation)screen.orientation.addEventListener("change",function(event){_handleResize(event)})};var initializeAddPortletNameToPopup=function(html,popup){jQuery("[data-abx-popup-portlet]",html.scriptless).each(function(id,element){var e=jQuery(element);var portletName=
e.attr("data-abx-popup-portlet");if(portletName&&portletName!="")jQuery(popup.element).parent(".ui-dialog").addClass(portletName)})};var removePortletNameFromPopup=function(popup){jQuery("[data-abx-popup-portlet]",popup.getContent()).each(function(id,element){var e=jQuery(element);var portletName=e.attr("data-abx-popup-portlet");if(portletName&&portletName!="")jQuery(popup.element).parent(".ui-dialog").removeClass(portletName)});popup.unsetDisplayedPart()};jQuery(registerEventHandlers);this.internals=
{handleSubmitError:_handleSubmitError,handlePopupResponse:handlePopupResponse,fillPopup:fillPopup,closePopupDelayed:closePopupDelayed};return{displayType:displayTypePopup,mode:mode,setTitle:setTitle,isVisible:popupIsVisible,isElementInPopup:isElementInPopup,currentZIndex:currentZIndex,getPopup:getPopup,closePopup:closePopup,openLink:openLink,submitForm:submitForm,needsPopupHandling:needsPopupHandling,setMode:setMode,sendUsingYahoo:Abaxx.ajax.sendForm,registerEventHandlers:registerEventHandlers}});
Abaxx.define("util",function(){var idsToSelector=function(){var ids=[];jQuery.each(jQuery.makeArray(arguments),function(index,arg){jQuery.merge(ids,jQuery.makeArray(arg))});return jQuery.map(ids,function(id){return"[id\x3d'"+id+"']"}).join(",")};var reloadImage=function(imageId){var src=jQuery("[id\x3d'"+imageId+"']").attr("src");if(src){var seq=(new Date).getTime();var r=/(\?|&)seq=\d+/;if(r.exec(src))src=src.replace(r,"$1seq\x3d"+seq);else src=src+(src.indexOf("?")===-1?"?seq\x3d":"\x26seq\x3d")+
seq;jQuery("[id\x3d'"+imageId+"']").attr("src",src)}};var _leftPadZero=function(value,targetLength){targetLength=targetLength||2;for(var padded=value.toString();padded.length<targetLength;)padded="0"+padded;return padded};var formatTime=function(millis){var seconds=Math.floor(millis/1E3)%60;var minutes=Math.floor(millis/(60*1E3))%60;var hours=Math.floor(millis/(60*60*1E3))%24;var formatted="";if(hours>0)formatted=_leftPadZero(hours)+":";formatted+=_leftPadZero(minutes)+":"+_leftPadZero(seconds);return formatted};
var registerEnterKeyListener=function(item,action){jQuery(item).keypress(function(event){if(event.which===13)action(item,item.form,event)})};var print=function(){window.print()};var concatURL=function(baseURL,params){var url=baseURL;if(params)if(url.indexOf("#")>0)url=concatURL(url.substring(0,url.indexOf("#")),params)+url.substring(url.indexOf("#"),url.length);else url+=(url.indexOf("?")===-1?"?":"\x26")+params;return url};var enableAction=function(id,enabled){if(jQuery.isArray(id))jQuery.each(id,
function(index,element){enableAction(element,enabled)});jQuery("#"+id+", #"+id+"Top, #"+id+"Bottom, #"+id+"DropDown").each(function(index,element){enableElement(element,enabled)})};var enableElement=function(element,enabled){if(jQuery.isFunction(element.enableAction))element.enableAction(enabled);else{var e=jQuery(element);if(enabled){e.prop("disabled",false).removeAttr("disabled").removeClass("abaxx-disabled");if(e.attr("href")=="javascript: void(0)"&&e.attr("data-xhref")!=null)e.attr("href",e.attr("data-xhref"))}else{e.prop("disabled",
true).attr("disabled","disabled").addClass("abaxx-disabled");if(e.attr("href")!=null&&e.attr("data-xhref")!=null)e.attr("href","javascript: void(0)")}}};Abaxx.core.onReady(function(){jQuery("a[disabled]").each(function(index,element){enableElement(element,false)})});return{idsToSelector:idsToSelector,reloadImage:reloadImage,formatTime:formatTime,registerEnterKeyListener:registerEnterKeyListener,concatURL:concatURL,enableAction:enableAction,enableElement:enableElement,print:print}});
Abaxx.define("html5compat.placeholders",function(){if(document.createElement("input").placeholder===undefined){var hidePlaceholderText=function(input){var $input=jQuery(input);var placeholder=$input.attr("placeholder");$input.addClass("focus").removeClass("placeholderVisible");if($input.val()===placeholder)$input.val("")};var showPlaceholderText=function(input){var $input=jQuery(input);var placeholder=$input.attr("placeholder");var currentValue=$input.val();$input.removeClass("focus").toggleClass("placeholderVisible",
currentValue===placeholder);if(currentValue==="")$input.val(placeholder)};jQuery(document).on("submit abx_ajax_submit","form",function(){jQuery("input[placeholder]").each(function(index,element){var $input=jQuery(element);if($input.val()===$input.attr("placeholder"))$input.val("")})}).on("blur","input[placeholder]",function(){showPlaceholderText(this)}).on("focus","input[placeholder]",function(){hidePlaceholderText(this)});jQuery("input[placeholder]").each(function(index,input){showPlaceholderText(input)})}});
Abaxx.define("html5compat.autofocus",function(){if(document.createElement("input").autofocus===undefined)jQuery(function(){jQuery("form [autofocus]").focus()})});
Abaxx.define("widgets.contextMenu",function(){function init(options){var $menu=jQuery("\x3cul /\x3e").contextmenu(options);return $menu.data("contextmenu")}function forElement(selector){return jQuery(selector).data("contextmenu")}function initializeContextMenus(){jQuery("[data-abx-widget\x3dcontext-menu]").each(function(id,element){var menuOptions=jQuery(element).data("abxOptions");if(!menuOptions.trigger)menuOptions.trigger=element;init(menuOptions)})}Abaxx.core.onReady(initializeContextMenus);return{init:init,
forElement:forElement}});
Abaxx.define("widgets.dialog",function(){function initializeDialogs(){jQuery("[data-abx-widget\x3ddialog]").each(function(id,element){var dialog=jQuery(element);var options=dialog.data("abxOptions");if(!options.callback||options.callback=="Abaxx.widgets.dialog.show")show(options.message);else eval(options.callback+"('"+options.message+"');");dialog.remove()})}var show=function(message,options){var infoPopup=jQuery("#infoPopup");if(infoPopup.length===0)infoPopup=jQuery("\x3cdiv id\x3d'infoPopup' /\x3e");infoPopup.html(message.replace(/\n/g,
"\x3cbr /\x3e")).dialog(options).on("dialogclose",function(event,dialog){jQuery(event.target).dialog("destroy");jQuery(event.target).remove()})};var close=function(){jQuery("#infoPopup").dialog("close")};var setupDialogTriggers=function(){Abaxx.core.companionScript("data-abx-web-dialog-closer",function(trigger,data){var closeDialog=function(event){if(event.type==="keypress"&&event.keyCode!=13)return;trigger.parents("[data-abx-web-dialog]").dialog("close")};trigger.off(".abx-web-dialog-close");if(trigger.is("select"))trigger.on("change.abx-web-dialog-close",
closeDialog);else if(trigger.is("input"))trigger.on("keypress.abx-web-dialog-close",closeDialog);else trigger.on("click.abx-web-dialog-close",closeDialog)});Abaxx.core.companionScript("data-abx-web-dialog-open",function(trigger,data){var button=trigger;trigger.off("click.abx-web-dialog-open").on("click.abx-web-dialog-open",function(event$$0){event$$0.preventDefault();var dialogTemplate=jQuery("[id\x3d'"+data.dialog+"']");data=data||{};var defaultOptions={minHeight:0,minWidth:0,resizable:false,position:{my:"left top",
at:"left bottom",of:button}};var options=jQuery.extend(defaultOptions,data);var setFocus=function(event,ui){jQuery(event.target).find(":input").first().focus()};dialogTemplate.dialog(options).on("dialogopen",setFocus).on("dialogfocus",setFocus).on("dialogclose",function(event,dialog){try{jQuery(event.target).dialog("destroy")}catch(e){Abaxx.log.error(e)}});Abaxx.ajax.triggerHtmlChangedEvent({changed:dialogTemplate});dialogTemplate.show()})})};Abaxx.core.onReady(initializeDialogs);setupDialogTriggers();
return{show:show,close:close}});
Abaxx.define("widgets.form",function(){var addInfos=function(form,aspectName,infos){jQuery(form).find("[data-abx-form-row]").each(function(index$$0,element$$0){var formRow=jQuery(element$$0);var dataFormRow=formRow.data("abxFormRow");if(dataFormRow.aspect==aspectName){var data=formRow.data("abxWebFormrowMessages");data.totalCountErrors=0;data.totalCountWarning=0;data.totalCountInfos=0;var infoAreaFormRow=data.infoarea;if(infoAreaFormRow.messages.length==0)infoAreaFormRow.messages[0]={aspectName:aspectName};
var newInfos=infos;jQuery(infoAreaFormRow.messages).each(function(index,element){if(element.aspectName===aspectName){element.errors=newInfos.errors;element.warnings=newInfos.warnings;element.infos=newInfos.warnings;if(typeof newInfos.errors!="undefined")data.totalCountErrors+=newInfos.errors.length;if(typeof newInfos.warnings!="undefined")data.totalCountWarning+=newInfos.warnings.length;if(typeof newInfos.infos!="undefined")data.totalCountInfos+=newInfos.infos.length;if(typeof newInfos.errors!="undefined"&&
newInfos.errors.length>0){data.infoarea.highestMessageType="error";data.infoarea.hasEntries=true;data.infoarea.hasMessages=true;Abaxx.theme.messages.highlightAspects(formRow,true,"error");Abaxx.theme.messages.highlightAspects(formRow,false,"warning");Abaxx.theme.messages.highlightAspects(formRow,false,"info")}else if(typeof newInfos.warnings!="undefined"&&newInfos.warnings.length>0){data.infoarea.highestMessageType="warn";data.infoarea.hasEntries=true;data.infoarea.hasMessages=true;Abaxx.theme.messages.highlightAspects(formRow,
false,"error");Abaxx.theme.messages.highlightAspects(formRow,true,"warning");Abaxx.theme.messages.highlightAspects(formRow,false,"info")}else if(typeof newInfos.infos!="undefined"&&newInfos.infos.length>0){data.infoarea.highestMessageType="info";data.infoarea.hasEntries=true;data.infoarea.hasMessages=true;Abaxx.theme.messages.highlightAspects(formRow,false,"error");Abaxx.theme.messages.highlightAspects(formRow,false,"warning");Abaxx.theme.messages.highlightAspects(formRow,true,"info")}else{data.infoarea.highestMessageType=
"help";data.infoarea.hasEntries=data.infoarea.hasHelp;data.infoarea.hasMessages=false;Abaxx.theme.messages.highlightAspects(formRow,false,"error");Abaxx.theme.messages.highlightAspects(formRow,false,"warning");Abaxx.theme.messages.highlightAspects(formRow,false,"info")}data.hasErrors=data.totalCountErrors>0;data.hasWarnings=data.totalCountWarning>0;data.hasInfos=data.totalCountInfos>0;return false}});if(newInfos.help&&newInfos.help.length>0)jQuery(infoAreaFormRow.help).each(function(index,element){if(element.aspectName===
aspectName){element.help=newInfos.help;if(typeof newInfos.help!="undefined"&&newInfos.help.length>0){data.infoarea.hasEntries=true;data.infoarea.hasHelp=true;Abaxx.theme.messages.highlightAspects(formRow,true,"help")}else{data.infoarea.hasHelp=false;Abaxx.theme.messages.highlightAspects(formRow,false,"help")}return false}});return false}})};return{addInfos:addInfos}});