(function(){function s(){var a=0;try{a=window.performance.timing.navigationStart+Math.floor(window.performance.now())}catch(b){}return 0>=a?(new Date).getTime():a}function W(){if("string"!==typeof document.title){var a=document.getElementsByTagName("title")[0];return a.innerText||a.textContent}return document.title}function q(a,b){var c=-1;b&&(c=a.indexOf(b));return c}function Lb(a,b){return G(a,b)}function Pa(){return Qa?new Qa:Ra?new Ra("MSXML2.XMLHTTP.3.0"):window.XMLHttpRequest?new window.XMLHttpRequest:
new window.ActiveXObject("MSXML2.XMLHTTP.3.0")}function C(a,b){return parseInt(a,b||10)}function S(a){var b,c,d,e=document.cookie.split(";");for(b=0;b<e.length;b++)if(c=q(e[b],"="),d=e[b].substring(0,c),c=e[b].substring(c+1),d=d.replace(/^\s+|\s+$/g,""),d===a)return"DTSA"===a.toUpperCase()?decodeURIComponent(c):c;return""}function Mb(a){document.cookie=a+'="";path=/'+(l.domain?";domain="+l.domain:"")+"; expires=Thu, 01-Jan-70 00:00:01 GMT;"}function X(a,b,c){b||0==b?(b=(""+b).replace(/[;\n\r]/g,"_"),
b="DTSA"===a.toUpperCase()?Y(b):b,a=a+"="+b+";path=/"+(l.domain?";domain="+l.domain:""),c&&(a+=";expires="+c.toUTCString()),document.cookie=a):Mb(a)}function u(a,b){for(var c=1;c<arguments.length;c++)a.push(arguments[c])}function Nb(a){if(a){var b=a.indexOf("lastModification=");if(0<=b)try{return parseInt(a.substring(b+17),10)}catch(c){}}return 0}function ld(){return v}function md(){var a=document.location;return a?0===q(a.href,"file"):!1}function nd(a){return!a||1!==a.length||"undefined"===typeof l.featureHash?
!1:-1!==q(l.featureHash,a)}function od(a){var b=t.dT_;if(b.ism(a)&&-1===q(b.iMod(),a))return b.iMod(a),!0;b.ism(a)&&t.console&&t.console.log("WARNING: "+('Module "'+a+'" already enabled!'));return!1}function pd(a,b){if(a){var c=/([a-zA-Z]*)[0-9]*_[a-zA-Z_0-9]*_[0-9]+/g.exec(a);if(c&&c.length){var d=c[0];l.csu=c[1];c=d.split("_");l.featureHash=c[1];l.dtVersion=f.version[0]+""+f.version[1]}}if(b){c=b.split("|");for(d=0;d<c.length;d++){var e=q(c[d],"=");-1===e?l[c[d]]="1":l[c[d].substring(0,e)]=c[d].substring(e+
1,c[d].length)}}if(l.xb){ca=Ob(l.xb);try{ca=RegExp(ca)}catch(A){}}}function qd(a){a&&(l.initializedModules+=a);return l.initializedModules}function rd(a){return l[a]}function sd(a){var b;if("object"==typeof a){b=[6,3,0,0];for(var c=0;c<b.length;c++){if(a[c]<b[c])return!1;if(a[c]>b[c])break}return!0}return a&&383<=a}function td(){return l.csu}function Da(a){return a?String.trim?a.trim():a.replace(/^\s+|\s+$/g,""):null}function Sa(a,b){if(a.indexOf)return a.indexOf(b);for(var c=a.length;c--;)if(a[c]===
b)return c;return-1}function Z(a,b,c){a==window?Pb?Pb(b,c,!0):Ta&&Ta("on"+b,c):a.addEventListener?a.addEventListener(b,c,!0):a.attachEvent&&a.attachEvent("on"+b,c);for(var d=!1,e=T.length;0<=--e;){var f=T[e];if(f.object===a&&f.event===b&&f.handler===c){d=!0;break}}d||u(T,{object:a,event:b,handler:c})}function Qb(a,b,c){for(var d=T.length;0<=--d;){var e=T[d];if(e.object===a&&e.event===b&&e.handler===c){T.splice(d,1);break}}a==window?Rb?Rb(b,c,!0):ud&&Ta("on"+b,c):a.removeEventListener?a.removeEventListener(b,
c,!0):a.detachEvent&&a.detachEvent("on"+b,c)}function Ua(a){try{var b=a.tagUrn;return b&&-1!==q(b,"schemas-microsoft-com:vml")}catch(c){return!0}}function vd(a){if(!a||-1===a.indexOf("://"))return null;a=a.split("/")[2].split(":")[0].toLowerCase();return/^[^<>%/\\\(\)\{\}\[\] ]+$/.test(a)?a:null}function wd(a){a=a?a:t.location.pathname;var b=t.location.search;b&&(b.length&&"?"===b.charAt(0))&&(b=b.substring(1));a=31+Sb(a);a=31*a+Sb(b);return"RID_"+(a&a)}function Sb(a){var b=0;if(a)for(var c=a.length,
d=0;d<c;d++)b=31*b+a.charCodeAt(d),b&=b;return b}function da(a,b){try{t.sessionStorage[a]=b}catch(c){X(a,b)}}function Tb(a){try{if(t.sessionStorage)return t.sessionStorage[a]}catch(b){}return S(a)}function Y(a){a=encodeURIComponent(a);var b=[];if(a)for(var c=0;c<a.length;c++){var d=a.charAt(c),e=xd[d];e?u(b,e):u(b,d)}return b.join("")}function y(a){var b=[];if(a)for(var c=0;c<a.length;c++){var d=a.charAt(c),e=yd[d];e?u(b,e):u(b,d)}return b.join("")}function zd(a){a=a.replace(/_/g,"_5F").replace(/%/g,
"_25");return y(a)}function Ob(a){-1<q(a,"^")&&(a=a.split("^^").join("^"),a=a.split("^dq").join('"'),a=a.split("^rb").join(">"),a=a.split("^lb").join("<"),a=a.split("^p").join("|"),a=a.split("^e").join("="),a=a.split("^s").join(";"),a=a.split("^c").join(","),a=a.split("^bs").join("\\"));return a}function $(a){var b=a.length;if("number"===typeof b)a=b;else{for(var b=0,c=2048;a[c-1];)b=c,c+=c;for(var d=7;1<c-b;)d=(c+b)/2,a[d-1]?b=d:c=d;a=a[d]?c:b}return a}function M(a){if(a){for(var b=[],c=0;c<a.length;c++){var d=
a.charAt(c),e=l.spc;e||(e="");e+=Ad;-1===q(e,d)&&u(b,d)}a=b.join("")}return a||""}function Va(){var a=document.location;if(a){var a=a.href,b=q(a,"#");0<=b&&(a=a.substr(0,b));return a}return"-"}function oa(a,b){a=Math.floor(a);(b||Wa)&&0<a&&X(pa,a)}function Xa(){return t.performance&&t.performance.timing&&(!v.ff||9<v.ff)?t.performance:null}function Bd(a,b,c,d){if(Object.defineProperty&&(!v.ie||8<v.ie)){ea[b]=a[b];var e=function(c){ea[b]=c;d&&d.apply(a,[c]);return ea[b]};try{Object.defineProperty(a,
b,{get:function(){return c?c.apply(a,null):ea[b]},set:e,configurable:!0})}catch(f){}}}function Cd(a,b){if(a[b]&&Object.defineProperty&&(!v.ie||8<v.ie)){var c=a[b];try{delete a[b],ea[b]=null,a[b]=c}catch(d){Object.defineProperty(a,b,{get:function(){return ea[b]},configurable:!0})}}}function Dd(a,b,c,d){if(l.ffi)return!0;for(var e=!1,f=e,h=e,g=0;g<a.length&&(!e||!f);g++)a[g]=a[g].split("."),e=a[g][0]==b,f=a[g][1]==c,!h&&(e&&c>a[g][1])&&(h=!0);a=e&&f||h;if(!e||!f)h?qa(d+" version ("+b+"."+c+") official not supported. Instrumentation active nonetheless, because major version is supported and minor is newer than supported versions."):
qa(d+" not instrumented because version ("+b+"."+c+") not supported.");return a}function Ed(a){X("dtUseDebugAgent",a)}function Fd(a){X("dt_dbg_console",a)}function Gd(a){return(0==q(a,"http")||0==q(a,"//"))&&q(location.href,location.host)!=q(a,location.host)}function Ya(a){var b=document.createElement("a");b.href=a;return b.cloneNode(!0).href}function Za(){try{return window.location.href}catch(a){}return""}function Hd(a){try{var b=window;if(!b.location)return a;var c=b.location,d=c.origin;if(!d){if(!c.protocol||
!c.host)return a;d=c.protocol+"//"+c.host}var e=Ya(a);return e.substr(0,d.length+1).toLowerCase()===(d+"/").toLowerCase()?e.substr(d.length):e}catch(f){return a}}function Id(a,b,c){return a.apply(b,c)}function Jd(){return J}function Ub(a){var b=[];if(a&&"-"!==a){a=a.split("p");for(var c=0;c<a.length;c++){var d=a[c].split("h");if(2===d.length&&d[0]&&d[1]){var e=d[0],f=e.split("_"),f=C(f[0]),h=s()%$a;h<f&&(h+=$a);f+9E5>h&&u(b,{frameId:e,actionId:d[1]})}}}return b}function ab(a){return/^[0-9A-Za-z_\$\+\/\.\-\*%\|]*$/.test(a)}
function Ea(){var a=S(fa);return a&&ab(a)?a:""}function Kd(){var a=Ea();if(a){var b=a.indexOf("|");-1!==b&&(a=a.substring(0,b))}return a}function bb(){var a=Ub(S(Fa));if(0<a.length){for(var b=[],c=0;c<a.length;c++)a[c].frameId!==J&&u(b,a[c]);Vb(b)}}function Vb(a,b){var c="";if(a){for(var c=[],d=0;d<a.length;d++)0<d&&0<c.length&&u(c,"p"),u(c,a[d].frameId),u(c,"h"),u(c,a[d].actionId);c=c.join("")}c||(c="-");X(Fa,c)}function Ld(a){a=J+"h"+f.esc(a);var b=S(Fa);return b&&0<=q(b,a)&&!f.hyb()?null:a}function Md(){return fa}
function Nd(){return Od}function Pd(){return Wb}function Qd(a){a=y(a);cb[a]||(cb[a]="1")}function Rd(a){return"1"===cb[a]}function Sd(a,b){if("string"===typeof a)return a===b;for(var c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0}function db(){var a=f;try{for(var b=U;b&&b!==self;){if(b.dT_)return b.dT_.tdto();b=b!==b.parent?b.parent:!1}}catch(c){}return a}function Td(){return!ra}function Ud(){var a=Pa();"withCredentials"in a||(a=window.XDomainRequest?new XDomainRequest:null);return a}function eb(a,
b,c,d,e){for(var f=3,h=0;0<f;)try{var g,k=l.cors;g=k?Ud():Pa();if(!g)break;h=s();a&&a(g,b,d,h);"onreadystatechange"in g?g.open("POST",b,c):g.open("POST",b);"setRequestHeader"in g&&(g.setRequestHeader("Content-Type","text/plain;charset=UTF-8"),e&&!k&&g.setRequestHeader(Wb,e));c&&("timeout"in g&&"ontimeout"in g)&&(g.timeout=l.xt||2E3,g.ontimeout=function(a){return function(){try{a.abort()}catch(b){}}}(g));g.send(d);f=0}catch(m){f--}}function Xb(a,b){var c;try{c=navigator.sendBeacon(a,b||"")}catch(d){c=
!1}return c}function Yb(){return Vd&&!l.app&&!l.cors&&!l.dsndb&&!l.spl&&!v.ff}function Zb(){var a=this;a.vals=[];a.a=function(b,c){u(a.vals,[b,c])};a.g=function(b){for(var c=0;c<a.vals.length;c++)if(a.vals[c][0]===b)return a.vals[c][1]};a.s=function(){for(var b=0,c=0;c<a.vals.length;c++)b+=(""+a.vals[c][0]).length+(""+a.vals[c][1]).length+1;return b}}function Ga(a,b,c,d){a=$b(a,b,c);w&&ac(c,d,a)}function $b(a,b,c){var d="",e=null,A=null,h=null;if(a){e="";fb=0;var A=!1,g="",d=h="",k;for(k in n)if(n.hasOwnProperty(k)){var m=
n[k];if(gb(m))A||(A=!0,qa("Maximum open actions exceeded configured amount of "+(l.moa||30)+", dropping action "+m));else{var e=e?e+",":e,r=bc(n[k],!1,!1,!0);r&&!g&&(g=m.getReferer());h=m.getReferer();d=m.getTitle();e+=r}}e={actions:e,referer:g,sourceUrl:h,sourceTitle:d}}else{e="";A=D.length;b&&(n=[]);d=h=k="";if(0<A){for(m=0;m<A;m++)if((r=bc(D[m],!0,c,!1))&&0<r.length)k||(k=D[m].getReferer()),h=D[m].getReferer(),d=D[m].getTitle(),"_load_"==D[m].type&&(Wa=!0,z&&(e=z.delayed?"d|"+z.actionId+"|"+z.name+
"|"+z.type+"|"+z.info+"|"+z.frameId+"|"+z.start+"|"+z.location+"|"+z.title:"s|"+z.actionId+"|"+z.name+"|"+z.type+"|"+z.info+"|"+z.frameId+"|"+z.start,h=z.location,d=z.title,z=null)),0<e.length&&(e+=","),e+=r;D=[];for(g in n)n.hasOwnProperty(g)&&u(D,n[g])}e={actions:e,referer:k,sourceUrl:h,sourceTitle:d}}k=e;d=k.actions;e=k.referer;A=k.sourceUrl;h=k.sourceTitle;w=null;if(0<d.length){w=new Zb;w.a("a",Y(d));w.a("v",l.dtVersion);w.a("fId",J);a&&w.a("PV",1);f.pageId!==J&&w.a("pId",f.pageId);hb&&w.a("pFId",
hb);w.a("rId",l.rid);w.a("rpId",l.rpid);if(!a){a:{k=(g=Xa())?g.timing:!1;if(g&&k&&(g=k.domComplete,k=k.domContentLoaded,g||k)){k=g?g:k;break a}k=ib}k&&w.a("domR",k)}jb(c)&&w.a("unload","xhr");cc(a,b);dc=!1}else!1===dc&&(w||(w=new Zb),c=w.vals.length,cc(a,b),w.vals.length>c?(w.a("fId",J),w.a("v",l.dtVersion)):w=null);return{referer:e,sourceUrl:A,sourceTitle:h}}function cc(a,b){for(var c=0;c<kb.length;c++)kb[c](w,a,b)}function ec(){for(var a=[],b=0;b<w.vals.length;b++)0<b&&u("$"),u(a,"$",w.vals[b][0],
"=",w.vals[b][1]);return a.join("")}function fc(){var a=ec(),b=v.ie?1500:7E3;l.msl&&(b=Math.min(b,C(l.msl)));return 0===a.length%b?C(a.length/b):C(a.length/b)+1}function Wd(a,b,c){var d=document.createElement("img");d.onerror=function(){oa((s()-b)/2)};d.setAttribute("src",c+"?"+a)}function ac(a,b,c){if(!f.disabled){var d=c.referer,e=c.sourceUrl,A=c.sourceTitle;c=Za();d==c&&(d="");w.a("url",encodeURIComponent(c));w.a("title",Y(M(W()).substring(0,100)));var h=w.g("a"),g=h&&("s"===h.charAt(0)||"d"===
h.charAt(0));(g||h&&-1===h.indexOf("_load_"))&&w.a("vd",s()-ga);e&&(e!=c&&!g)&&(w.a("sUrl",encodeURIComponent(e)),w.a("sTitle",A&&A!=W()?Y(M(A).substring(0,100)):"-"));h=s();w.a("time",h);var e=v,k;if(A=a&&Yb())g=!0,b=!1;else{var m=l.fsc,g=l.fso,r=e.op&&15<=e.op&&!g;k=fc();g=!a||a&&!(e.sf||e.op&&!r||e.ff&&(1<k||l.sffs||17<e.ff)||e.ie&&(9>e.ie||l.sies)||Ha||e.msf||e.ab||e.ch&&(22<e.ch||m));b&&(g=!1);(b=(1==k||r)&&a&&(e.ie&&9>e.ie||e.ch&&!m||r))&&l.cors&&(b=g=!1)}l.fa&&(g=!0);a=g;m=b&&!d;b=!1;g=l.cors;
k=ec();r=null;if((l.spl||m)&&!g){var q=v.ie?1500:7E3;l.msl&&(q=Math.min(q,C(l.msl)));var t=fc(),p,y=s(),n=0;if(1<t){if(100>t)for(var r=[],x=0;x<t;x++){var z="sid="+y+"&p"+(x+1)+"_"+t+"=";l.app&&(z="app="+l.app+"&"+z);n+q<=k.length?(p=k.slice(n,n+q),"%"==p.charAt(p.length-1)&&k.length>=n+q+1&&(p+=k.charAt(n+q),p+=k.charAt(n+q+1),n+=2),"%"==p.charAt(p.length-2)&&k.length>=n+q+2&&(p+=k.charAt(n+q),n+=1)):p=k.slice(n);u(r,z+p);n+=q}}else r=[k]}else r=[k];k=r;if(null!==k){r=l.reportUrl?l.reportUrl:"dynaTraceMonitor";
if(m&&!d)for(d=0;d<k.length;d++)Wd(k[d],h,r);else{h=r;m=k[0];r=!1;g?(h+="?"+fa+"="+(encodeURIComponent(Ea())||"null"),h+=";"+pa+"="+encodeURIComponent(S(pa)),h+=";referer="+encodeURIComponent(d||c),r=!0):A&&d&&(h+="?"+fa+"="+(encodeURIComponent(Ea())||"null"),h+=";"+pa+"="+encodeURIComponent(S(pa)),h+=";referer="+encodeURIComponent(d||c),r=!0);if(l.spl&&!g)for(c=0;c<k.length;c++)A=h,m=null,r||(A+="?"),A+=k[c],eb(gc,A,a,m,d);else l.app&&(h+=(r?";":"?")+"app="+l.app),A?(Xb(h,m),b=!0):eb(gc,h,a,m,d);
if(!b&&(e.ch&&22>=e.ch||e.ff&&1<k.length))for(d=s();25>s()-d;);}ga=s()}}}function Xd(){sa||(sa=document.createElement("doc:rdy"));if(sa.doScroll){var a=function(){try{sa.doScroll("left"),sa=null,ib=s(),K()}catch(b){G(a,0)}};a()}else document.addEventListener("DOMContentLoaded",function(){ib=s();K()},!1)}function Yd(a){ha(a)}function ha(a){if(ta){var b=!1;a?s()+a<hc&&(b=!0):b=!0;b&&(clearTimeout(ic),ta=!1)}ta||(hc=s()+(a||0),a?(ic=G(jc,a||0),ta=!0):jc())}function jc(){ta=!1;Ga(!1,!1,!1,!1)}function Zd(a){u(kb,
a)}function $d(a,b,c){Ga(b,c,!1,a)}function ae(){return!!f.disabled}function K(){for(var a=0;a<lb.length;a++)lb[a]()}function kc(){return n}function ia(a,b,c,d,e,f,h,g,k,m){var r={actionId:be++,start:c,stop:d,type:a,name:b,info:h,domNodes:e,next:[],sendNextPreview:null,previewCountMax:null,parentActionId:null,parentActionLinkType:null,parentFrameActionName:null,simpleName:null,websocketRequestID:f?C(2147483647*Math.random())+1:0,parent:null,referer:location.href,title:W(),xhrUrl:g,customAction:k,
xhrWrapper:m,getReferer:function(){return r.parent?r.parent.getReferer():r.referer},getTitle:function(){return r.parent?r.parent.getTitle():r.title},add:function(a){a&&a.name&&u(r.next,a)}};r.timeoutId=Lb(function(){if(r&&(r.shouldTimeout=!0,!r.stop&&!mb(r))){var a="Action timed out!";r.xhrWrapper&&(a+=" Readystate: "+r.xhrWrapper.readyState+", xhr url: "+g+", status: "+r.xhrWrapper.status);qa(a);V(r.actionId)}},1E3*C(l.oat||180));return r}function mb(a){for(var b=0;b<a.next.length;b++)if(!a.next[b].stop||
mb(a.next[b]))return!0;return!1}function lc(){var a=!1,b=[],c;for(c in n)if(n.hasOwnProperty(c)){var d=n[c];0<d.previewCountMax&&(s()>d.sendNextPreview&&(d.sendNextPreview+=6E4,u(b,d)),a=!0)}0<b.length&&Ga(!0,!0,!1,!1);for(c=0;c<b.length;c++)b[c].previewCountMax--;a&&G(lc,1E3)}function mc(a,b){if(a)for(var c=null,d=0;d<a.length;d++)if(c=a[d],c.actionId==b||c.next&&(c=mc(c.next,b),null!==c))return c;return null}function nb(a){var b=null;D&&(b=mc(D,a));return b}function Ia(a,b,c,d,e,f,h,g,k){c||(c=
s());a=ia(b,a,c,null,null,e,f,h,g,k);"boolean"==typeof d&&d&&(d=x);if(d){if(b=null,b="number"==typeof d?nb(d):"object"==typeof d?d:x){b.add(a);a.parent=b;ob(a);for(var m in n)n.hasOwnProperty(m)&&(n[m]&&n[m].sendNextPreview>a.start+1E4)&&(n[m].sendNextPreview=a.start+1E4)}}else ob(a),nc(a),u(n,a),x=a,u(D,a),a.sendNextPreview=a.start+1E4,a.previewCountMax=100,G(lc,5E3);return a}function ob(a){if(x!=a)if(x&&(Ja=x),x=a){a=a.actionId;for(var b=Ub(S(Fa)),c=!1,d=0;d<b.length;d++)b[d].frameId===J&&(b[d].actionId=
Y(a),c=!0);c||u(b,{frameId:J,actionId:Y(a)});Vb(b)}else bb()}function V(a,b,c){b||(b=s());var d=[];if(D)for(var e=0;e<D.length;e++){var f=oc(D[e],a,b,c);"string"!==typeof f&&(d[e]=f)}a=!1;b=[];for(c=0;c<D.length;c++)d[c]?a=d[c]:(mb(D[c])||u(b,D[c].actionId),Q=null);d=[];for(c in n)n.hasOwnProperty(c)&&(e=n[c],0<=Sa(b,e.actionId)?u(d,c):N&&(f=ja.gca(),e.parentActionLinkType=U&&f[f.length-1]==N?"S":"A",N=null));for(c=0;c<d.length;c++)n.splice(d[c],d[c]-(d[c]||NaN)+1||n.length);d=a;ha();ob(d)}function oc(a,
b,c,d){var e,f,h=a.actionId==b;if(h){a.stop=c;d&&(a.start=d);a.domNodes=$(document.getElementsByTagName("*"));a.timeoutId&&window.clearTimeout&&window.clearTimeout(a.timeoutId);var g=a.parent;if(g&&!g.stop&&g.shouldTimeout){var k=!1;for(f=0;f<g.next.length;f++)if(!g.next[f].stop&&g.next[f].actionId!=b){k=!0;break}k||G(function(){g.stop||V(g.actionId,c)},0)}}else a.stop||(e=a);k=!1;if(a.next&&a.next.length)for(f=1;f<=a.next.length;f++){var m=oc(a.next[a.next.length-f],b,c,d),l="string"===typeof m,
k=k||l||m&&m.found===b;l||(e=m||e);if((k||h)&&e)break}if(h||k)"object"===typeof e?e.found=b:e="found";return e}function bc(a,b,c,d){if(a.parentFrameActionName){var e=[],f=["0"];f[1]=a.parentActionId;f[2]=y(a.parentFrameActionName);f[3]=a.parentActionLinkType;e[0]=f.join("|");e[1]=pb(a,1,b,c,d).result;return!e[1]?null:e.join(",")}return pb(a,1,b,c,d).result||null}function pb(a,b,c,d,e){a.domNodes||(a.domNodes=$(document.getElementsByTagName("*")));var f=[];if(a.next&&0<a.next.length){for(var h=0;h<
a.next.length;h++){var g=a.next[h],g=pb(g,b+1,c,d,e),k=g.result;if(k)f.push(k);else if(!g.exceeded)return{}}if(c)for(h=0;h<a.next.length;h++)if(g=a.next[h],g.stop)a.stop&&g.stop>a.stop&&(a.stop=g.stop);else{a.stop=!1;break}}if(!d&&!e&&(!a.stop||0==a.stop))return{};c=[];c[0]=b.toString();c[1]=a.actionId;c[2]=y(a.simpleName||a.name);c[3]=y(a.type);c[4]=a.info?y(a.info):"-";c[5]=a.start;c[6]=a.stop||0;c[7]=a.domNodes;c[8]="-";c[9]="-";c[10]="-";c[11]="-";c[12]="-";c[13]="-";e=8;1==b&&a.childFrameActions&&
(c[8]=a.childFrameActions,e=9);a.websocketRequestID&&(c[9]=a.websocketRequestID,e=10);if(a.xhrUrl&&(!v.ie||7<v.ie))c[10]=y(a.xhrUrl),e=11;a.customAction&&(c[11]="1",e=12);b=document.referrer;"_load_"===a.name&&b&&(c[13]=y(b),e=14);c.splice(e,c.length-e);b=!1;a.stop||d||a.next&&a.next.length||!gb(a)?(f.unshift(c.join("|")),fb++):gb(a)&&(b=!0);a={exceeded:b};1<f.length?a.result=f.join(","):f[0]&&(a.result=f[0]);return a}function gb(a){var b=C(l.moa)||30,c=["_warning_","_error_","_log_","_rv_","_rs_"];
return fb+1>b&&-1==Sa(c,a.type)}function jb(a){if(0<qb||a&&0<R.length)if(a=R.length,0<a)return R[a-1];return null}function pc(a,b,c,d,e,f){if(ca&&ca.exec&&d&&ca.exec(d))return null;ua&&(Ha=!0);var h=null;b||(b=3);var g=aa(),k="";g&&(g.info=a||"-",k=g.info);var m=jb(!1);!m&&(g&&g.actionId)&&(m=g.actionId);d=d?Hd(d):null;m?h=qc(m):g?3<=b&&(h=rb(g.getName(),g.type,g.start,null,c,k,d,e,f),g.actionId=h):x?1<=b&&(h=qc(x.actionId,a,"xhr",s(),c,k,d,e,f)):l.cux&&(h=rb("Unlinked XHR","xhr",s(),null,c,k,d,e,
f));return h}function rb(a,b,c,d,e,f,h,g,k){a=Ia(a,b,c,d,e,f,h,g,k);a.usage=1;O[a.actionId]=a;return a.actionId}function qc(a,b,c,d,e,f,h,g,k){a=O[a];var m=-1;a?(a.usage++,m=a.actionId):x&&(m=rb(b,c,d,x.actionId,e,f,h,g,k));return m}function sb(a){var b;try{var c;a:{try{if(a&&L&&L.getEntriesByName){var d=Ya(a);0==q(d,"/")?d=location.protocol+"//"+location.host+d:0!=q(d,"http")&&(d=location.href.substr(0,location.href.lastIndexOf("/")+1)+d);var e=L.getEntriesByName(d);if(e.length){c=e[e.length-1];
break a}}}catch(f){}c=null}if(c)return oa((c.requestStart-c.startTime)/2),!0}catch(h){}return!1}function ce(a,b,c,d){c?G(function(){sb(b)},0):sb(b);d=d||s();G(function(){if(!Ha){var b=d,c=0;if(c=O[a])c.usage--,c=c.usage,0>=c&&(V(a,b),O[a]=null,delete O[a])}},de);return 1>=ee()?(K(),!0):!1}function fe(a){a&&(u(R,a),qb++)}function ge(a){a&&(qb--,G(function(){for(var b=-1,c=R.length-1;-1==b&&0<=c;)R[c]==a&&(b=c),c--; -1!=b&&(b==R.length-1?R.pop():R.splice(b,1))},0))}function he(a){a&&(a.usage=1)}function ee(){var a=
0,b;for(b in O)if(b&&O.hasOwnProperty(b))try{a+=O[b].usage}catch(c){}return a}function nc(a){N=null;if(ja){var b=ja.gca();if(N=b[b.length-1])a.parentActionId=N.actionId,a.parentFrameActionName=N.name,N.childFrameActions?N.childFrameActions++:N.childFrameActions=1}}function va(a,b,c){var d=s();a=M(a);b=ia(b,a,d,d,-1);(c=wa(b,c))&&ha();return c}function wa(a,b){var c;if(c="undefined"==typeof b||null==b?x:nb(b))return c.add(a),!1;nc(a);u(D,a);return!0}function ie(){va("visit end","_endVisit_",-1)}function je(a,
b){if(ka<=(f.cfg("mepp")||10))ka++,va(a,"_error_",b)}function qa(a,b){va(a,"_warning_",b)}function ke(a,b){va(a,"_log_",b)}function le(a){a=pc(a,3,!0);return!a?null:nb(a)}function me(a){return a.websocketRequestID}function ne(a){return a.actionId}function oe(a){isNaN(a)||(a=O[a]);return a?a.getReferer():null}function pe(a,b){var c=s(),c=ia("_rv_",a+"="+b,c,c,0);wa(c);ha()}function qe(a,b,c){var d=s();a=ia("_rs_",a+"="+b,d,d,0);wa(a,c);ha()}function re(){return x}function rc(){return x?x.name:null}
function sc(a){var b=a==rc();if(!Ja)return!b;a=a===Ja.name&&3E3>=s()-Ja.start;return!b&&!a}function se(){return!x||0<x.stop}function te(a){return O[a]}function ue(a,b,c,d,e,f,h){if(4>arguments.length||"undefined"==typeof d)d=!0;return Ia(a,b,c,d,null,e,f,h).actionId}function ve(a,b,c){K();V(a,b,c)}function we(){return Wa}function xe(a){return a.actionId}function ye(a,b){tc(null,null,null,null,a,b)}function tc(a,b,c,d,e,f){if((a||e)&&ka+1<=ze){ka++;"string"==typeof e||e instanceof String?(a||(a=e),
e={}):e=e||t.event||{};var h=e.message||e.name||e.description||a||e.errorMessage||"Indeterminable error name",g=e.fileName||e.filename||e.sourceURL||e.errorUrl||e.file||b||"",k=e.lineNumber||e.lineno||e.line||e.errorLine||c||-1,m=(e.columnNumber?e.columnNumber+1:void 0)||e.errorCharacter||e.colno||e.column||d||-1,l=uc(e)||Ae(),p=aa()||!1,q=e.number||e.code||e.errorCode||-1;300<h.length&&(h=h.substring(0,300));var n=s(),n=ia("_error_",M(h),n,n,-1);f=wa(n,f);if(n){g&&(0<=k&&(g+="|"+k),0<=m&&(g+="|"+
m),xa("_location_",g,n));if(l){if(1200<l.length){k=l.split(/(\r\n|\n|\r)/gm);m="";for(l=0;l<k.length&&!(0<k[l].trim().length&&(m+=k[l]+"\n"),1200<m.length);l++);l=m}k=l.replace(/(\r\n|\n|\r)/gm,"|");xa("_stack_",k,n)}q&&xa("_code_",q,n);p&&xa("_useraction_",p.type+"|"+p.getName(),n);"Indeterminable error name"==h&&(h=ya("msg",a),h+=ya("file",b),h+=ya("line",c),h+=ya("column",d),h+=ya("error",e),xa("_debug_",h,n));f&&ha()}}}function Ae(){try{throw Error("");}catch(a){var b=uc(a);if(b&&4<b.split(/\r\n|\r|\n/).length)return"<generated>\n"+
b}var b=[],c=0;try{for(var d=arguments.callee.caller.caller;d&&10>b.length;){var e=Be.exec(d.toString());b.push(e?e[1]||"[a]":"[a]");d=d.caller;c++}}catch(f){}return 3<c?"<generated-ie>\n"+b.join("\n"):null}function uc(a){a=a||{};var b=a.stack||a.backtrace||a.stacktrace||!1;return!b&&a.error?a.error.stack:b}function xa(a,b,c){var d=s();a=ia(a,M(b),d,d,-1);wa(a,c.actionId)}function ya(a,b){var c,d=typeof b;c=""+(a+"|")+(d+"|");if("object"===d)for(var e in b)b.hasOwnProperty(e)&&("stack"!=e&&"error"!=
e)&&(c+=e+"|",d=typeof b[e],c+=d+"|","object"!==d&&"function"!==d&&(c+=b[e]+"|"));else c+=b+"|";return c}function tb(a){if(a)for(var b=document.getElementsByTagName("LABEL"),c=$(b),d=0;d<c;d++)if(b[d].htmlFor==a)return a=b[d],I(a.innerText,a.textContent);return null}function I(a){for(var b=0;b<arguments.length;b++){var c=arguments[b];if(c&&"string"==typeof c&&Da(c))return Da(c)}return null}function vc(a){if(a){if(0===q(a,"data:"))return null;a=a.split("/");if(0<a.length)return a[a.length-1].split(".")[0]}return null}
function wc(a){if(a&&a.split){var b=a.split("/");if(0<b.length&&(b=Da(b[b.length-1]),null!==b))return b}return a}function xc(a,b){var c=b.nodeName?b.nodeName.toUpperCase():ub,d=b.type&&"string"===typeof b.type?b.type.toUpperCase():null,e=null;switch(a){case la.LABEL:c==za&&d!=vb&&(c=d&&(d==wb||d==yc||d==zc||d==xb)?b.value:null,e=tb(b.id),e=d&&(d==wb||d==yc||d==zc)?I(c,e):I(e,c));e||(e=I(b.textContent,b.innerText));break;case la.NAME:if(c==za&&d!=vb||c==wb)e=I(b.name,b.title,d&&d==xb?b.alt:null);break;
case la.OTHER:c==za&&d==xb?e=vc(b.src):c==Ac?e=I(b.title,wc(b.href)):c==Ce?e=I(b.name,b.title,b.alt,vc(b.src)):c==De&&(e=I(b.name,b.id,b.action));e||(e=I(b.title,b.data,b.wholeText,b.id));break;case la.CLASS:e="object"==typeof b.className?b.baseVal||b.animVal:b.className;break;case la.TAG:c==za&&d!=vb?e=za+": "+d:c==Ac?e="LINK":Aa||(Aa=e=c)}return e}function Bc(a){if(!a)return null;try{if(v.ie&&Ua(a))return"VML Node";var b=a.nodeName?a.nodeName.toUpperCase():ub;if(b==Cc||b==Dc||b==Ec||b==Fc)return Aa;
for(b=0;4>=b;b++){var c=xc(b,a);if(c&&c!==Aa)return c}return Bc(a.parentNode)}catch(d){}return null}function Gc(a,b){if(!b)return null;var c=$(b);if(0>=c||20<Ka)return null;for(var d=0;d<c;d++){var e=b[d];if(v.ie&&Ua(e))return"VML Node";var f=null;Ka++;if(f=Gc(a,e.childNodes))return f;Ka--;if(f=xc(a,e))return f}return null}function Ee(a){Aa=null;try{if(v.ie&&Ua(a))return"VML Node";if("string"==typeof a)return a;if(a.attributes){var b=a.attributes["data-dtName"];if(b&&b.value)return b.value}var c=
a.nodeName?a.nodeName.toUpperCase():ub;if(c==Cc||c==Dc||c==Ec||c==Fc)return"Page: "+Fe;if(c==Hc){var d;if(a){var e=a.nodeName?a.nodeName.toUpperCase():null;if(e!=Hc)d=null;else{var f=tb(a.id),h=I(f,a.name,e),b=null;if(!a.multiple){var g=a.options&&-1<a.selectedIndex?a.options[a.selectedIndex]:null;g&&(b=I(g.label,g.innerText,g.textContent))}d=b?"["+h+"] to value ["+b+"]":h}}else d=null;return d}if(c==Ic){var k;if(a){var l=a.nodeName?a.nodeName.toUpperCase():null;if(l!=Ic)k=null;else{var n=tb(a.id);
k=I(n,a.name,l)||a.nodeName}}else k=null;return k}var p=Da(I(a.innerText,a.textContent));if(p)return p;Ka=0;if(a.childNodes&&0<$(a.childNodes))return la.foreach(Gc,[a])}catch(q){}return Bc(a)}function Jc(a,b,c,d){if(f!=B)return B.bi(a,b,c,d);try{d||(d=30);var e={id:Ge++,htmlObject:a,name:null,type:b,info:c?c:"-",start:s(),sourceActionCreated:!1,validUntil:s()+d,getName:function(){if(!e.name){var a="";(a=l.uam?"dTMasked_"+e.htmlObject.nodeName:M(Ee(e.htmlObject)))||(a="-");var b=l.sl||100;a.length>
b&&(a=a.substring(0,b-3)+"...");e.name=a}return e.name},isSourceActionCreated:function(){return e.sourceActionCreated},setSourceActionCreated:function(){var a=e;do a.sourceActionCreated=!0,a=a.next;while(a)}};Kc&&(e.next=H,e.next&&(e.next.prev=e),H=e);return e}finally{e&&(a=e.validUntil-s(),0>=a?yb(e):G(function(){yb(e)},a))}}function aa(){if(f!=B)return B.gci();try{if(H){for(var a=H,b=H.next;b;){var c;if(c=b.htmlObject!=a.htmlObject)a:{try{for(var d=b.htmlObject.parentNode;d;){if(d==a.htmlObject){c=
!0;break a}d=d.parentNode}}catch(e){}c=!1}c&&(a=b);b=b.next}return a}return null}catch(l){return null}}function Lc(){return f!=B?B.ci():aa()?H.getName():null}function He(){return f!=B?B.cit():aa()?H.type:null}function Ie(){return f!=B?B.cih():aa()?H.htmlObject:null}function Ba(){return f!=B?B.gpi():Ca}function Mc(){return f!=B?B.pi():Ba()?Ca.getName():null}function Je(){return f!=B?B.pit():Ba()?Ca.type:null}function Nc(){return f!=B?B.piv():Ba()?Ca.validUntil:null}function Oc(){for(var a=H;a;)a.htmlObject=
null,a=a.next;H=null}function yb(a){if(f!=B)return B.ei(a);if(H){for(var b=H;b.next&&b!==a;)b=b.next;b===a&&(Lc()&&(Ca=H),b.htmlObject=null,b.prev?b.prev.next=b.next:H=b.next,b.next&&(b.next.prev=b.prev))}}function P(a,b,c){var d=!1,e=l.doNotDetect?l.doNotDetect.split(","):null;if(c&&e)for(var f=0;f<e.length;f++)e[f]==c&&(d=!0);d||(b||(b=a),Z(document,a,function(a){var c=null;a.target?c=a.target:a.srcElement&&(c=a.srcElement);var d=b;if(("KD"==d||"KU"==d)&&"password"!==c.type)if(a=a.keyCode?a.keyCode:
a.charCode)if(l.uam){var e=String.fromCharCode(a);"a"<=e&&"z">=e||("A"<=e&&"Z">=e||"0"<=e&&"9">=e)||(d+=a)}else d+=a;Jc(c,d,null,30)}))}function Ke(a){(Kc=a)||Oc()}function zb(){var a=Ab;if(F){if(5E3<Math.abs(F.responseStart-Ab))return Ab;var b=F.redirectStart,c=F.navigationStart,d=F.fetchStart,e=c+6E4;c&&(b?a=e>b?c:b:d&&(a=e>d?c:d))}return Math.floor(a)}function Le(a){a||s()}function Pc(){ma--;if(0==ma&&ba)for(var a=0;a<Bb.length;a++)try{Bb[a]()}catch(b){}if(0>=ma){var a=F?F.loadEventEnd:0,c;c=F?
F.loadEventStart:0;c=c<zb()?0:c;if(ba){if(a&&c&&a>c){var d=s()-a;if(5E3<(0>d?-1*d:d))a+=d;V(ba.actionId,a,c)}else V(ba.actionId);ba=!1}Qc||Rc()}a=db();a!=f&&a.sole()}function Rc(a){if(na){var b=0;L&&!a&&(b=F?F.loadEventEnd:0);b?V(na.actionId,b):V(na.actionId);na=null;K()}}function Me(){Rc(1)}function Ne(){ma++}function Oe(){Qc=!0}function Sc(){na&&!ba&&(ba=Ia("_onload_","_load_",null,na))}function Pe(a){u(Bb,a)}function Qe(a){u(lb,a)}function Re(a){u(Cb,a)}function Se(){if(!Tc||0<ma)Tc=!0,K(),Pc()}
function Uc(){K();if(!Db){var a=db();a!=f&&a.iolm();Sc();Db=!0;G(Se,0)}}function Te(){"loaded"==document.readyState&&K();"complete"==document.readyState&&Uc()}function Eb(){K();Db||("complete"==document.readyState?Vc?Ga(!1,!0,!1,!1):(Vc=!0,G(Eb,3E3)):G(Eb,3E3))}function Ue(){Fb();var a;if(0<La.length){a=Yb();for(var b=0;b<La.length;b++)try{var c=La[b];a?Xb(c.path,c.data):eb(null,c.path,!1,c.data)}catch(d){}}if(!Wc)try{Oc();a=T;for(var e=a.length;0<=--e;){var f=a[e];Qb(f.object,f.event,f.handler)}T=
[];L=F=Ra=Qa=null;Wc=!0}catch(h){}Ma||(Ma=!0,bb())}function Ve(){Fb(!0);Ma||(Ma=!0,bb())}function We(){var a=Tb("dtSa");da("dtSa","-");if(a&&"-"!=a&&(a=a.split("|"),10==a.length)){var a={delayed:"true"==a[0],type:a[1],actionId:a[2],name:a[3],info:a[4],start:a[5],frameId:a[6],location:a[7],title:a[8],viewDurationStart:a[9]},b=!1;f!=f.tdto()&&(b=f.tdto().iRO(a.location));if(!document.referrer||a.location==y(document.referrer)||a.location==y(document.location)||b)Q=z=a,ga=a.viewDurationStart}}function Xc(a,
b,c,d){var e=jb(!0);c=c||s();!e&&a&&b&&c?da("dtSa","true|"+y(b)+"|-1|"+y(a)+"|"+y(d||"-")+"|"+c+"|"+J+"|"+y(Va())+"|"+y(M(W()).substring(0,100))+"|"+ga):e&&Q?(da("dtSa","false|"+Q.type+"|"+Q.actionId+"|"+Q.name+"|"+Q.info||"-|"+c+"|"+Q.frameId+"|"+y(Va())+"|"+y(M(W()).substring(0,100))+"|"+ga),Q=null):x&&"_load_"!=x.name&&da("dtSa","false|"+y(x.type)+"|"+x.actionId+"|"+y(x.name)+"|"+y(x.info||"-")+"|"+c+"|"+J+"|"+y(Va())+"|"+y(M(W()).substring(0,100))+"|"+ga)}function Yc(){Fb()}function Fb(a){var b=
s();if(!ua||Ha){ua=!a;for(a=0;a<Cb.length;a++)Cb[a](ua);a=$b(!1,!0,!0);var c=aa();if(!c){var d=Ba();d&&(sc(Mc())&&3E3>=s()-Nc())&&(c=d)}c&&!1===c.isSourceActionCreated()?(c.setSourceActionCreated(),Xc(c.getName(),c.type,c.start,c.info)):Xc(null,null,b,null);if(v.sf&&t.frames)for(b=0;b<t.frames.length;b++)try{t.frames[b].dT_&&t.frames[b].dT_.obc()}catch(e){}w&&ac(!0,!1,a)}}function Xe(){return 0>=ma}function Ye(a){Zc?a(E.bwsW,E.bwsH):u(Gb,a)}function Ze(){var a=document,b=a.documentElement,c=0,d=0,
e=a.body;if("number"===typeof self.innerWidth)c=self.innerWidth,d=self.innerHeight;else if(a&&(b.clientWidth||b.clientHeight))c=b.clientWidth,d=b.clientHeight;else if(e&&(e.clientWidth||e.clientHeight))c=e.clientWidth,d=e.clientHeight;if(0>c||0>d){var f;E.gBI().ie?f=140:f=10;c=Math.max(c,f);d=Math.max(d,10)}a=c;E.bwsW=a;E.bwsH=d;Zc=!0;for(b=0;b<Gb.length;b++)Gb[b](a,d)}function $e(){if(!L)return null;var a=L.timing||{},b=L.navigation||{},c=a.navigationStart;return 0<c?(b=["a",b.type,"b",c],b=$c(a,
b),b.join("")):null}function $c(a,b,c){c=c?a.startTime:a.navigationStart;for(var d in ad){var e=a[ad[d]];e&&e>=c&&(b.push(d),b.push(Math.round(e-c)))}return b}var bd=window;if(bd.dT_)bd.console&&console.log("Duplicate agent injection detected, turning off redundant core.");else{var Ab=s(),ga=s(),pa="dtLatC",t=window,G=t.setTimeout,Qa=t.XMLHttpRequest,Ra=t.ActiveXObject,U=t.parent,f={version:"1007"},f={version:[6,3,7,"1007"]};f.version[3]=parseInt(f.version[3],10);t.dT_||(document.dT_=window.dT_,t.dT_=
f);f.dC=Mb;f.io=q;f.sC=X;f.gC=S;f.gx=Pa;f.st=Lb;f.nw=s;f.pn=C;f.ap=u;var v=[],p=navigator.userAgent;try{var cd=/Firefox[\/\s](\d+\.\d+)/,af=/(iPod|iPhone|iPad)/,bf=/AppleWebKit/;if(0<=q(p,"MSIE"))v.ie=C(p.substr(p.lastIndexOf("MSIE")+5,3));else if(0<=q(p,"Trident"))0<=q(p,"rv:")?v.ie=C(p.substr(p.lastIndexOf("rv:")+3,2)):0<=q(p,"rv ")&&(v.ie=C(p.substr(p.lastIndexOf("rv ")+3,2)));else if(0<=q(p,"Edge"))v.edge=C(p.substr(p.lastIndexOf("Edge")+5,2));else if(0<=q(p,"Android"))v.ab=parseFloat(p.substr(q(p,
"Android")+8,3));else if(p.match(af)&&p.match(bf)){var Hb=/Version\/([0-9]*\.[0-9]*)/;p.match(Hb)||(Hb=/OS ([0-9]*_[0-9]*)/);v.msf=parseFloat(p.match(Hb)[1])}else if(("Safari"===navigator.appName||-1<q(p,"Safari"))&&-1===q(p,"Chrom"))v.sf=C(p.substr(p.lastIndexOf("Version/")+8,1));else if(t.opera)v.op=C(t.opera.version().split(".")[0]);else if(0<=q(p,"OPR/"))v.op=C(p.match(/OPR\/([0-9]*\.[0-9]*)/)[1]);else if(cd.test(p)){var dd=C(p.match(cd)[1]);v.ff=-1===dd?0:dd}else{var Ib=q(p,"Chrom");-1<Ib&&(v.ch=
C(p.substring(Ib+7,Ib+9)))}}catch(cf){}f.gBI=ld;f.hyb=md;var l={reportUrl:"dynaTraceMonitor",initializedModules:"",csu:"dtagent",domainOverride:"false"},ca,ed=document.getElementsByTagName("script"),fd=$(ed);if(0<fd)for(var Na,Jb=fd-1;0<=Jb;Jb--)if(Na=ed[Jb],Na.attributes){var gd=Na.attributes.getNamedItem("data-dtconfig");if(gd){pd(Na.src,gd.value);break}}f.gAN=td;f.smbi=od;f.isc=sd;f.cfg=rd;f.ism=nd;f.iMod=qd;var Ad="\t\n\r",hd=window.sessionStorage,Pb=window.addEventListener,Ta=window.attachEvent,
Rb=window.removeEventListener,ud=window.detachEvent,T=[],xd={"!":"%21","~":"%7E","*":"%2A","(":"%28",")":"%29","'":"%27",$:"%24",";":"%3B",",":"%2C"},yd={"^":"^^","|":"^p",",":"^c",";":"^s"},ea={};f.tau=Ya;f.icr=Gd;f.aIOf=Sa;f.ael=Z;f.rel=Qb;f.lv=Tb;f.sv=da;f.gh=vd;f.cvs=Dd;f.esc=Y;f.aesc=y;f.rsc=M;f.tpesc=zd;f.ulc=oa;f.gP=Xa;f.apl=Bd;f.rpl=Cd;f.dbg=Ed;f.dbc=Fd;f.gEL=$;f.rxapply=Id;f.loc=Za;f.de=Ob;var $a=6E8,Fa="dtPC",fa="dtCookie",Od="x-dtPC",Wb="x-dtReferer",J=s()%$a+"_"+C(1E3*Math.random());f.frameId=
J;f.gFId=Jd;f.gDtc=Kd;f.gSCN=Md;f.gPCHN=Nd;f.gRHN=Pd;f.gPAH=Ld;f.pageId=null;f.pageTitle=null;f.frameCount=0;var ra=null,hb,ja,cb={};try{U&&(U!==self&&U.dT_&&Sd(U.dT_.version,f.version))&&(ja=U.dT_,ra=U.dT_.tdto())}catch(df){}ra?(f.pageId=ra.pageId,f.pageTitle=ra.pageTitle,hb=ja.frameId,ja.frameCount++):(f.pageId=J,f.pageTitle=W());f.tp=Td;f.tdto=db;f.aFU=Qd;f.iRO=Rd;var gc=function(a,b,c,d){function e(a){var c=s()-d;sb(b)||oa(c/2);for(var c=a&&a.split("|"),e=1;e<c.length;e++){var m=c[e].split("=");
if(m[0]==fa)m=decodeURIComponent(m[1]),ab(m)&&X(fa,m);else if("name"==m[0]){m=a;try{if(t.localStorage){var n=l.csu+"_"+l.app+"_Store",p=t.localStorage.getItem(n),q=Nb(p);Nb(m)>=q&&t.localStorage.setItem(n,m)}}catch(u){}}else"enabled"==m[0]&&"false"==m[1]&&(da("dtDisabled",!0),f.disabled=!0)}}function n(a){ua&&v.sf&&La.push({path:b,data:c})}"onreadystatechange"in a||(a.onload=function(){e(a.responseText)});a.onreadystatechange=function(){if(a&&4==a.readyState)try{200==a.status?e(a.responseText):n(a.status)}catch(b){n(0)}finally{a=
null}}},Vd=navigator&&"sendBeacon"in navigator,w=null,kb=[],ta=!1,ib,dc=!0,sa=!1,ic,hc,La=[];f.id=ae;f.ss=$d;f.asl=Zd;f.sMPS=Yd;var x=null,Ja=null,D=[],n=[],fb=0,qb=0,R=[],O=[],N,Wa=!1,Ha=!1,de=v.msf?1E3:0,be=1;f.getCurrentOpenRootActions=kc;var lb=[];f.gid=xe;f.ea=ue;f.la=ve;f.lx=ce;f.ex=pc;f.ec=fe;f.lc=ge;f.eV=ie;f.pe=je;f.pw=qa;f.pl=ke;f.rv=pe;f.rs=qe;f.pcn=va;f.ewa=le;f.gWRI=me;f.gAID=ne;f.ca=re;f.can=rc;f.isci=sc;f.noa=se;f.ti=K;f.las=we;f.gca=kc;f.gAR=oe;f.gAA=te;f.ru=he;var Be=/function\s*([\w\-$]+)?\s*\(/i,
ka=0;setInterval(function(){0<ka&&ka--},3E4);var ze=f.cfg("mepp")||10;f.re=tc;f.rex=ye;var wb="BUTTON",za="INPUT",vb="HIDDEN",yc="SUBMIT",zc="RESET",xb="IMAGE",Ce="IMG",Ac="A",De="FORM",Fc="#DOCUMENT",Cc="HTML",Dc="BODY",Ec="HEAD",Hc="SELECT",ub="unknown",Ic="TEXTAREA",Fe=wc(Za()),Aa=null,la={LABEL:0,NAME:1,OTHER:2,CLASS:3,TAG:4,foreach:function(a,b){for(var c=0;4>=c;c++){var d=a(c,b);if(d)return d}return null}},Ka=0,H,Ca=null,Ge=0,Kc=!0,B=f.tdto();P("click","C","clk");P("mousedown","D","mdw");P("mouseup",
"U","mup");P("dblclick","CC","dcl");P("keydown","KD","kyd");P("keyup","KU","kyu");P("scroll","S","scr");P("touchstart","TS","tcs");P("touchend","TE","tce");if(l.ade){var Oa=l.ade.split(",");if(Oa&&0<Oa.length)for(var Kb=0;Kb<Oa.length;Kb++)P(Oa[Kb])}f.bi=Jc;f.ei=yb;f.gci=aa;f.ci=Lc;f.cit=He;f.cih=Ie;f.gpi=Ba;f.pi=Mc;f.pit=Je;f.piv=Nc;f.aad=Ke;var Db=!1,Tc=!1,Vc=!1,z=null,Q=null;We();var ba=null,Ma=!1,Bb=[],Cb=[],ua=!1,Wc=!1,ma=1,id=document.location;id&&f.tdto().aFU(id.href);l.rid||(l.rid=wd(l.ridPath));
var F=null,Qc,L=Xa();L&&(F=L.timing)&&oa((F.requestStart-F.navigationStart)/2,!0);f.sls=Le;f.sole=Pc;f.iolm=Ne;f.solb=Sc;f.slem=Oe;f.lst=zb;Z(t,"beforeunload",Yc);Z(t,"unload",Ue);Z(t,"pagehide",Ve);Z(document,"readystatechange",Te);G(Eb,3E3);Z(t,"load",Uc);Xd();var na=Ia("_load_","_load_",zb(),null);K();f.all=Pe;f.ail=Qe;f.apll=Re;f.sle=Me;f.obc=Yc;f.ile=Xe;var E=window.dT_,Gb=[],Zc=!1;E.all(Ze);E.abwsl||(E.abwsl=Ye);var jd=!1;E.asl(function(a,b){if(!b&&!jd&&E.las()){jd=!0;var c=E.tdto(),d=function(a){return 0>
a||2147483647<=a||isNaN(a)?0:a};c?(a.a("w",d(c.bwsW)),a.a("h",d(c.bwsH))):(a.a("w",d(E.bwsW)),a.a("h",d(E.bwsH)))}});(function(){var a=E.gSCN();E.asl(function(b,c){if(!E.cfg("disableCookieManager")){var d=Ea();try{if("undefined"!=typeof window.sessionStorage){var e;a:{try{if(hd){e=hd[a];break a}}catch(f){}e=null}e=e||"";ab(e)||(e="");if(e&&"null"!=e&&d!=e){var h,g=e;if(g){var k=q(g,"|");-1!=k&&(g=g.substring(0,k))}h=g;if("undefined"!=typeof d&&null!=d&&""!=d){if((k=d)&&h)var l=q(k,"|"),k=-1!=l?h+
k.substring(l):h;d=k}else d=e}if(null!=d&&d){E.dC(a);E.sC(a,d);try{window.sessionStorage.setItem(a,d)}catch(n){}}}}catch(p){}}})})();var ad={c:"redirectStart",d:"redirectEnd",e:"fetchStart",f:"domainLookupStart",g:"domainLookupEnd",h:"connectStart",i:"connectEnd",j:"secureConnectionStart",k:"requestStart",l:"responseStart",m:"responseEnd",n:"domLoading",o:"domInteractive",p:"domContentLoadedEventStart",q:"domContentLoadedEventEnd",r:"domComplete",s:"loadEventStart",t:"loadEventEnd"},kd=!1;l.ntd||
f.asl(function(a,b){if(!b&&!kd&&f.las())if(kd=!0,"undefined"!=typeof L)if(v.ff&&9>=v.ff)a.a("nt","0");else{var c=$e();c?a.a("nt",c):a.a("nt","0")}else a.a("nt","0")});f.snt=$c}})();
(function(){function r(a,c,e){for(var g=2;g<arguments.length;g++)a.push(arguments[g]),(g<arguments.length-1||c)&&a.push("|")}function U(a,c){return a[12]<c[12]?1:a[12]==c[12]?0:-1}function V(a,m){for(var e=c.nw(),g=0;g<s.length;g++)if(s[g][1]==m)return;var g=c.ca(),f={};f[0]=a;f[3]=e;f[4]=0;f[1]=m;f[2]=g?g.name:"-";f[9]=!1;r(s,0,f)}function W(a,m,e,g){for(var f=0;f<s.length;f++){var d=s[f];if(d[1]==a){2<arguments.length&&0<e&&(d[3]=e);d[4]=3<arguments.length&&0<g?g:c.nw();d[7]=m;m||(d[9]=!1,d[10]=
!0);break}}}function X(a){if(c.re_t)for(var m=0,m=0;m<a.length;m++){var e=a[m];0===e[4]&&0<e[3]&&("i"===e[0]?(e[8]=!0,e[7]=!1,e[4]=c.nw()):(e[5]||(e[7]=!0),e[4]=e[3]));e[12]=e[4]?e[4]-e[3]:e[12]}}function F(a,m){var e=c.lst();X(a);if(0<a.length&&0<e){var g={},f;for(f=0;f<a.length;f++){var d=a[f],q=c.gh(d[1]);q&&0<q.length&&(g[q]||(g[q]=[]),r(g[q],0,d))}var p={},k=null;for(k in g)if(g.hasOwnProperty(k)&&g[k].length){q=g[k];q.sort(U);var l={};for(f=0;f<q.length;f++){var d=q[f],b=l[d[0]];b||(b={successful:0,
interrupted:0,failed:0,cached:0,withImpact:0,withNetworkTiming:0,impactIntervals:new N,w3cIntervals:new N,avgImpact:0,minImpact:e+99999999,maxImpact:0,avgNetworkTime:0,minNetworkTime:e+99999999,maxNetworkTime:0},l[d[0]]=b);if(d[3]&&d[4]){b.withImpact++;var h=d[4]-d[3];b.minImpact=b.minImpact<h?b.minImpact:h;b.maxImpact=b.maxImpact>h?b.maxImpact:h;b.avgImpact=c.pn((b.avgImpact*(b.withImpact-1)+h)/b.withImpact,10);b.impactIntervals.add(d[3]-e,d[4]-e)}if(d[5]&&d[6]){b.withNetworkTiming++;h=d[11];0>h&&
(h=d[6]-d[5]);if(0>h||3E5<h)h=0;b.minNetworkTime=b.minNetworkTime<h?b.minNetworkTime:h;b.maxNetworkTime=b.maxNetworkTime>h?b.maxNetworkTime:h;b.avgNetworkTime=c.pn((b.avgNetworkTime*(b.withNetworkTiming-1)+h)/b.withNetworkTiming,10);b.w3cIntervals.add(d[5],d[6])}b.successful+=d[7]?1:0;b.cached+=d[9]?1:0;d[7]||(b.interrupted+=d[8]?1:0,b.failed+=d[8]?0:1)}p[k]={maxDuration:0};for(var n in l)l.hasOwnProperty(n)&&(b=l[n],p[k].maxDuration=Math.max(b.maxImpact,b.maxNetworkTime),p[k][n]="i"==n||"s"==n?[b.successful,
b.failed,b.interrupted,b.cached,b.withImpact,b.withNetworkTiming,b.impactIntervals.getIntervalsAsString(),b.avgImpact,b.withImpact?b.minImpact:"0",b.maxImpact,b.w3cIntervals.getIntervalsAsString(),b.avgNetworkTime,b.withNetworkTiming?b.minNetworkTime:"0",b.maxNetworkTime].join("|"):"o"==n||"y"==n?[b.successful,b.failed,b.interrupted,b.cached,b.w3cIntervals.getIntervalsAsString(),b.avgNetworkTime,b.minNetworkTime,b.maxNetworkTime].join("|"):[b.successful,b.impactIntervals.getIntervalsAsString(),b.avgImpact,
b.minImpact,b.maxImpact].join("|"))}n=[];for(k in p)g.hasOwnProperty(k)&&r(n,0,k);0<y&&(q=n.sort(function(a,b){return p[b].maxDuration-p[a].maxDuration}),q.length>y&&(n=q.slice(0,y)));l=[];for(b=0;b<n.length;b++){k=n[b];q=g[k];f=p[k];0<l.length&&r(l,0,";");r(l,1,c.aesc(k),"featureHash");d=0;k=l.length-2;f.i&&(r(l,1,f.i),d+=2);f.s&&(r(l,1,f.s),d+=4);f.y&&(r(l,1,f.y),d+=8);f.o&&(r(l,1,f.o),d+=16);f.c&&(r(l,1,f.c),d+=32);l.pop();l[k]=d.toString(32);for(f=0;f<q.length&&f<G&&(q[f][12]>=B||q[f][11]>=B);f++)d=
q[f],r(l,0,","),r(l,0,d[0]+(d[7]?"":d[8]?"i":"f"),d[3]?d[3]-e:0,d[4]?d[4]-e:0,c.aesc(d[2]),c.tpesc(d[1])),d[5]&&r(l,0,"",d[5],d[6])}if(0>=l.length)return null;g=l.join("");m&&(g=m+"-"+e+";"+g);return c.esc(g)}return null}function Y(a,m,e){if(!m&&c.las())if(c.re_t&&c.gIA&&!O)if(c.gIA()&&!e)c.sMPS(1E3);else{O=!0;var g=F(s);g&&a.a("3p",g);s=[]}else if(c.re_r&&c.gSig&&(C=H("navigationStart"),!(0>=C)))if(m=H("loadEventEnd"),!e&&(0>=m||3E3>c.nw()-m))c.sMPS(2E3);else{if(m=Z())y=-1,G=0,I=1;var f=c.gSig(e);
e=z;var d=A;if(f&&0<f.length)for(var q=0;q<f.length;q++){var g=f[q].actionId,p=f[q].resources;if(c.gBI().op)for(var k=p,p=[],l=[],b=0;b<k.length;b++){var h=k[b];l[h.name]||(p.push(h),l[h.name]=!0)}k=[];for(l=0;l<p.length;l++){b=k;h=p[l];try{var n={};n[0]=$(h);n[11]=Math.round(h.duration);n[5]=P(h);var w=n,t;if(0<h.responseEnd){var u=C+h.responseEnd,u=u-c.lst();t=Math.round(u)}else u=c.nw(),t=Math.round(u-c.lst());w[6]=t;n[1]=h.name;var x=D.timing.loadEventEnd;n[2]=P(h)<=x?"_load_":"-";n[8]=0===h.responseEnd;
n[7]=c.gh(h.name)==E&&c.gBI().ie?0!=h.requestStart:0<h.responseEnd;n[9]=c.gBI().ch?0!=h.domainLookupStart&&0==h.requestStart:c.gh(h.name)!=E&&0===h.requestStart&&2>h.duration?!0:0>=h.responseEnd?!1:h.requestStart==h.fetchStart&&h.requestStart==h.responseStart&&h.responseStart!=h.responseEnd;b.push(n)}catch(B){}}k=k.concat(s);s=[];if(m){b=p;p=g;l=H("navigationStart");if(0>=b.length||0>=l)p=null;else{h=[];for(n=0;n<b.length&&!(n==Q&&0!=n);n++){var w=b[n],v=w.startTime;if(0<v){w=c.snt(w,["b",Math.round(v)],
!0);r(h,0,"|");v=b[n].name;if(0==J||v.length>K&&2==J)v=v.split("?")[0];r(h,0,c.tpesc(v.substring(0,K)),w.join(""))}}b=h.join("");b=p?p+"-"+l+";"+b:"-"+l+";"+b;p=c.esc(b)}p&&d.push(p)}(g=F(k,g))&&e.push(g)}else 0<s.length&&(g=F(s))&&e.push(g);t=e.length+d.length;z=R(a,e,"3p",!1);A=R(a,d,"rt",!0);L&&t==z.length+A.length&&(z=[],A=[]);0<A.length||0<z.length?(c.sMPS(1),L=!0):L=!1}}function R(a,c,e,g){var f=[];if(0<c.length)for(var d=0;d<c.length;d++){var q=a.s(),p=S-q;if(0==f.length&&p>aa&&(g||c[d].length<
p))if(q=e+(0<d?d:""),g){var k;k=c[d];var l=p;if(k.length<l)k=[k];else{var b=k.indexOf("%7C"),p=k.lastIndexOf("%7C",l),l=k.lastIndexOf("%7Cb",l);p==l&&(p=k.lastIndexOf("%7C",l-1));l=k.substring(0,b);b=k.substring(0,p);k=l+k.substring(p);k=[b,k]}a.a(q,k[0]);1<k.length&&f.push(k[1])}else a.a(q,c[d]);else f.push(c[d])}return f}function Z(){if(1E4==M)return!0;var a=c.gDtc();if(a){for(var m=0,e=0;e+1<a.length;e+=2)var g=a.charCodeAt(e),f=a.charCodeAt(e+1),m=m+(""+(g+f));return Math.floor(Math.abs(1E7*Math.sin(m)))%
1E4<M}return!1}function ba(a){var m=c.gh(a),e=-1!=a.indexOf("chrome-extension://")||-1!=a.indexOf("chrome://")||-1!=a.indexOf("data:")||-1!==a.indexOf("res://");a=-1!==a.indexOf("://localhost/")||-1!==a.indexOf("://localhost:")||m&&-1!==m.indexOf(T,m.length-T.length);return I?!e:!e&&!a&&m&&m!=E}function $(a){a=a.name.toLowerCase();-1<a.indexOf("ScriptResource.axd")?a="js":(a=a.substr(1+a.lastIndexOf("/")),0<a.indexOf("?")&&(a=a.split("?")[0]),0<a.indexOf("#")&&(a=a.split("#")[0]),a=0<a.indexOf(".")?
a.substring(a.lastIndexOf(".")+1):"-");switch(a){case "js":return"s";case "gif":case "png":case "jpg":case "jpeg":case "ico":case "tiff":case "bmp":case "xbm":case "svg":return"i";case "css":return"y";default:return"o"}}function H(a){return D&&D.timing?D.timing[a]:-1}function P(a){a=C+a.startTime;a-=c.lst();return Math.round(a)}function t(a,m){var e=c.cfg(a)?c.pn(c.cfg(a),10):m;return isNaN(e)?m:e}var c=window.dT_,D=c.gP(),C=null,L=!1,O=!1,B=500,G=3,I=!1,y=-1,M,Q,K,J,S,aa=3E3,E,T=".local",A=[],z=
[],N=function(){this.head=null;this.add=function(a,c){if(!(a>c)){var e={start:a,stop:c},g=this.head,f=null;if(g){for(;g&&a>g.start;)f=g,g=g.next;f?(e.next=f.next,f.next=e):(e.next=this.head,this.head=e)}else this.head=e,e.next=null}};this.reduce=function(){for(var a=this.head;a&&a.next;){for(;a.next&&a.stop+1>=a.next.start;)a.stop<=a.next.stop&&(a.stop=a.next.stop),a.next=a.next.next;a=a.next}};this.getIntervalsAsString=function(){this.reduce();for(var a=[],c=this.head;c;)0<a.length&&r(a,0,"_"),r(a,
0,c.start),r(a,0,"_"),r(a,0,c.stop),c=c.next;return a.join("")}},s=[];if(c.smbi("2")||c.syn&&!c.tpih){var u=(c.cfg("tp")?c.cfg("tp"):"500,50,3").split(","),x=u.length;if(!(3>x||5<x)){B=c.pn(u[0],10);G=c.pn(u[2],10);4<=x&&(I=c.pn(u[3],10));5<=x&&(y=c.pn(u[4],10));S=t("rtx",24E3);if(M=t("rt",0))Q=t("rtl",100),K=t("rtu",200),J=t("rtp",1);E=c.gh(c.loc());c.tpih=ba;c.tpstr=V;c.tpsto=W;c.asl(Y)}}})();
(function(){function s(b){a.tpsto(b.target.src,!0)}function t(){window&&(window.event&&window.event.srcElement)&&("loaded"==window.event.srcElement.readyState||"complete"==window.event.srcElement.readyState)&&a.tpsto(window.event.srcElement.src,!0)}function l(){for(var b=document.getElementsByTagName("script"),c=a.gEL(b),e=0;e<c;e++)try{var d=b[e];if(!d.dtInstrTime&&(d.dtInstrTime=a.nw(),""!=d.src&&a.tpih(d.src)&&(!d.attributes||!d.attributes["data-dtconfig"])))a.tpstr("s",d.src),a.gBI().ie&&11>a.gBI().ie?
a.ael(d,"readystatechange",t):a.ael(d,"load",s)}catch(f){}}function u(b){var c=null;b?b.target?c=b.target:b.srcElement&&(c=b.srcElement):window&&window.event&&(c=window.event.srcElement);c&&a.tpsto(c.src,!0)}function v(b){var c=null;b?b.target?c=b.target:b.srcElement&&(c=b.srcElement):window&&window.event&&(c=window.event.srcElement);c&&c.src!=a.loc()&&a.tpsto(c.src,!1)}function m(b){if(!b.dtInstrTime){b.dtInstrTime=a.nw();try{if(""!=b.src&&a.tpih(b.src)){a.tpstr("i",b.src);var c;c=b.complete?"undefined"!=
typeof b.naturalWidth&&0===b.naturalWidth?!1:!0:!1;c?a.tpsto(b.src,!0):(a.ael(b,"load",u),a.ael(b,"error",v),b.src=b.src)}}catch(e){}}}function n(){var b=document.getElementsByTagName("img"),c=a.gEL(b),e,d;for(e=0;e<c;e++)d=b[e],m(d);b=document.getElementsByTagName("input");c=a.gEL(b);for(e=0;e<c;e++)d=b[e],d.type&&"SUBMIT"==d.type.toUpperCase()&&m(d)}function p(){0<g&&2E3<a.nw()-g?(h=!1,a.sMPS(5E3)):(a.re_t&&(n(),l()),a.st(p,q))}function r(){a.tpsto?(n(),l(),a.ca()&&!h&&(g=a.nw(),h=!0,p())):a.st(r,
1)}function w(){return h}var a=window.dT_,q=30,g,h;if(a.smbi("3")){var f=(a.cfg("tp")?a.cfg("tp"):"500,50,3").split(","),k=f.length;3<=k&&5>=k&&(q=a.pn(f[1],10));a.re_t=!0;if((f=a.gP())&&f.timing)if(k=f.getEntriesByName||f.webkitGetEntriesByName,(f.getEntriesByType||f.webkitGetEntriesByType)&&k)a.re_t=!1;a.re_t&&(a.gIA=w,a.all(function(){g=a.nw()}),a.asl(function(){-1===g&&(g=a.nw())}),g=-1,r())}})();
(function(){function G(c){for(var a in c)c.hasOwnProperty(a)&&(r[a]=c[a]);return b.rxapply(s,this,arguments)}function H(c,a){function d(a){m||(m=!0,b.st(function(){b.lx(a,e)},0))}var e=c,m=!1;"object"===typeof c&&(a=c,e=(a.url||r.url)+"");a=a||{};for(var f in r)r.hasOwnProperty(f)&&!a.hasOwnProperty(f)&&(a[f]=r[f]);"function"===typeof a.data&&(a.type=a.type||a.callback,a.callback=a.data,a.data=!1);"string"===typeof a.success&&(a.success=!1);var h=b.ex("j"+v,3,void 0,e),p;(f=arguments)&&(1==f.length&&
"object"!==typeof c)&&(f=[arguments[0],a]);var n=a.beforeSend;a.beforeSend=function(a,c){if(h){var f=b.loc(),t=b.gPAH(h);t&&(b.icr(e)||a.setRequestHeader(b.gPCHN(),t),b.hyb()&&(f&&a.setRequestHeader(b.gRHN(),f),a.setRequestHeader("X-Host",b.gh(e))));(t=b.gAR(h))&&(t!=f&&!b.icr(e))&&a.setRequestHeader(b.gRHN(),t)}if(n){var g;try{g=b.rxapply(n,this,arguments)}catch(l){throw"TypeError"==l.name&&d(h),l;}return g}};if("undefined"===typeof a.async||a.async){var g=a.complete;a.complete=function(a,c){"success"!=
c&&b.pw('jQuery reported "'+c+'"');b.ec(h);var e;try{if(g)if("function"==typeof g)e=b.rxapply(g,this,arguments);else if(g.length)for(var f=0;f<g.length;f++)b.rxapply(g[f],this,arguments)}finally{b.lc(h),d(h)}return e};var l=a.success;l&&(a.success=function(a,c,e){b.ec(h);try{var f;if("function"==typeof l)f=b.rxapply(l,this,arguments);else if(l.length)for(var g=0;g<l.length;g++)b.rxapply(l[g],this,arguments)}finally{b.lc(h),d(h)}return f});var q=a.error;q&&(a.error=function(a,c,e){b.ec(h);var f;try{if("function"==
typeof q)f=b.rxapply(q,this,arguments);else if(q.length)for(var g=0;g<q.length;g++)b.rxapply(q[g],this,arguments)}finally{b.lc(h),d(h)}return f});var k=!0;try{p=b.rxapply(u,this,f);try{k=p&&p.statusText&&"canceled"==p.statusText}catch(s){k=!1}}finally{k&&d(h)}}else{b.ec(h);try{p=b.rxapply(u,this,f)}finally{b.lc(h),d(h)}}return p}function n(){!n.cache&&b.cfg("doNotDetect")&&(n.cache=b.cfg("doNotDetect").split(","));return n.cache}function B(c,a){var d=null,e=!1;switch(a){case "click":a="C";d="clk";
break;case "dblclick":a="CC";d="dcl";break;case "mouseup":a="U";d="mup";break;case "mousedown":a="D";d="mdw";break;case "keyup":a="KU";d="kyu";break;case "keydown":a="KD";d="kyd";break;case "scroll":a="S";d="scr";break;case "touchstart":a="TS";d="tcs";break;case "touchend":a="TE";d="tce";break;case "autocomplete":a="A";break;default:e=!0}var k=n();if(d&&k)for(var f=0;f<k.length;f++)k[f]==d&&(e=!0);return c&&!e?(d=function(d){var e=b.gci(),f;if(0==a.indexOf("KD")||0==a.indexOf("KU")){var g=d.keyCode?
d.keyCode:d.charCode;g&&(a=0==a.indexOf("KD")?"KD"+g:"KU"+g)}var g=a,k=d.target||d.currentTarget||d.srcElement||null;k&&(e||b.bi(k,g),f=b.rxapply(c,this,arguments));return f},d.dtHook=!0,d.origHandler=c,d):c}function k(c,a){var b=c[a];if(b)for(var e=0;e<b.length;e++)b[e].handler&&!b[e].handler.dtHook&&(b[e].handler=B(b[e].handler,a))}function I(c,a,d){var e=b.rxapply(w,this,arguments);"undefined"!=typeof e&&e&&"events"==a&&(k(e,"click"),k(e,"mouseup"),k(e,"mousedown"),k(e,"keydown"),k(e,"autocomplete"));
return e}function C(c,a){if(a)for(var d=0;d<a.length;d++)a[d].handler&&!a[d].handler.dtHook&&(a[d].handler=B(a[d].handler,a[d].type));d=window.jQuery;if(m)return b.rxapply(m,this,arguments);if(d&&d.event.handlers&&d.event.handlers!=C)return d.event.handlers.apply(this,arguments)}function J(){var c=arguments;3==c.length&&(c[2]&&"undefined"!==typeof c[2].origHandler)&&(c[2]=c[2].origHandler);return b.rxapply(x,this,c)}function z(){var c=window.jQuery;b.rpl(c,"data");b.rpl(c,"ajax");b.rpl(window,"jQuery");
v=c().jquery;!D&&K()&&(D=!0,b.ti(),u=c.ajax,c.ajax=H,s=c.ajaxSetup,c.ajaxSetup=G,w=c.data,(m=c.event.handlers)?c.event.handlers=C:c.data=I,c.fn&&(x=c.fn.off,c.fn.off=J),b.ael(window,"unload",function(){E||("undefined"!=typeof c&&(c.ajax=u,c.data=w,c.ajaxSetup=s,m&&(c.event.handlers=m),c.fn&&(c.fn.off=x)),s=x=m=w=u=null,E=!0)}))}function y(){var b=window.jQuery;b&&(b.data&&b.ajax&&b.ajaxSetup)&&z()}function K(){if("undefined"===typeof A){if(!v)return!1;var c=v.split(".");A=b.cvs("1.3 1.4 1.5 1.6 1.6 1.7 1.8 1.9 1.10 1.11 2.0 2.1".split(" "),
c[0],c[1],"jQuery")}return A}var b=window.dT_,s=null,m=null,w=null,u=null,E=!1,x=null,A,v,D=!1,F=!1,r={};n.cache=null;b.smbi("j")&&(b.initJQuery=z,b.apl(window,"jQuery",null,function(){!window.jQuery||!window.jQuery.ajax?F||(b.apl(window.jQuery,"ajax",null,y),b.apl(window.jQuery,"data",null,y),b.apl(window.jQuery,"ajaxSetup",null,y),F=!0):z()}),b.all(function(){y()}))})();
(function(){function w(a,d,c,h){e.push({url:d,actionId:a,start:c,stop:h,index:-1,resources:[]});b.sMPS(5E3)}function x(){for(var a=0;a<e.length;a++)if(0>e[a].index)return a;return null}function s(){var k=[];try{var d,c;if(d=document.getElementsByTagName("iframe"))for(c=0;c<d.length;c++)try{var h=d[c].contentWindow.performance.getEntriesByType("resource");h&&k.push.apply(k,h)}catch(l){}}catch(n){}d=x();c=e[d];try{var f=window.performance.getEntriesByType("resource");k.push.apply(k,f);for(f=0;f<k.length;f++){var g=
k[f],p=g.name;if(!(b.gh(g.name)==b.gh(b.loc())&&b.gBI().ch&&g.domainLookupStart<g.fetchStart))try{null!=c&&-1<g.name.indexOf(c.url)?(c.index=m.length-1,c=e[++d]):b.tpih(p)&&!(-1<p.indexOf(b.gAN()))&&(-1<p.indexOf(b.cfg("reportUrl"))||-1<p.indexOf("js.ruxit.com")||m.push(g))}catch(r){}finally{try{"function"===typeof q&&q.call(window.performance),b.st(function(){t.call(a)},0)}catch(s){}}}}catch(u){}}function y(a){s();for(var d=0,c=0,h=[],l=0;l<e.length;l++){var n=e[l],f=n.index;if(b.nw>n.stop+12E4)d++;
else{var g=-1;e.length>l+1&&(g=e[l+1].index);a||b.nw()>n.start+2E3?(f=0<g?m.slice(f,g):m.slice(f),0>=f.length?d++:(h.push({actionId:n.actionId,resources:f}),d++,c=g)):b.st(function(){b.sMPS(1E3)})}}e=e.slice(d);0<c&&(m=m.slice(c));return h}function z(){u=a.getEntriesByType||a.webkitGetEntriesByType;v=a.getEntriesByName||a.webkitGetEntriesByName;r=a.setResourceTimingBufferSize||a.webkitSetResourceTimingBufferSize;t=a.clearResourceTimings||a.webkitClearResourceTimings;var b=function(){};a.clearResourceTimings&&
(a.clearResourceTimings=b);a.webkitClearResourceTimings&&(a.webkitClearResourceTimings=b);return u&&v&&r&&t}function A(b){"function"===typeof a.addEventListener?a.addEventListener("resourcetimingbufferfull",b):"undefined"!==typeof a.onresourcetimingbufferfull?(q=a.onresourcetimingbufferfull,a.onresourcetimingbufferfull=b):"undefined"!==typeof a.onwebkitresourcetimingbufferfull&&(q=a.onwebkitresourcetimingbufferfull,a.onwebkitresourcetimingbufferfull=b)}var b=window.dT_,a=b.gP(),r,u,v,t,q,e=[],m=[];
if(b.smbi("r")||b.syn&&!b.re_r)window.externalHost?b.re_r=!1:a&&a.timing&&z()?(b.re_r=!0,r.call(a,500),b.irtx=w,b.gSig=y,A(s),e.push({start:b.lst(),index:0,resources:[]})):b.re_r=!1})();
